### ISSUE TITLE
Font size reduced

### ISSUE THREAD

**Issue by loshhilov** [jumpinjackie/mapguide-react-layout#1022]
After the last changes, the "External Base Layers" title font size was greatly reduced (less than in the layer list).
I found no other explicit display changes.

**Comment by jumpinjackie** [comment]
If you are referring to master, then that is probably the result of #597

**Comment by loshhilov** [comment]
Ok.
Yes, i testing only fresh master.

**Comment by loshhilov** [comment]
Yes,
this last master test

**Comment by jumpinjackie** [comment]
Please note, I'm making new 0.12.x releases from the [0.12.x branch](https://github.com/jumpinjackie/mapguide-react-layout/tree/0.12.x) where your other reported bugs should already be fixed (will be merged back into master later). Any new 0.12.x releases will be made off of this branch.
