### ISSUE TITLE
Map Component stops to update

### ISSUE THREAD

**Issue by joseaaz** [jumpinjackie/mapguide-react-layout#1063]
I tested with several maps and in all of them this  happened.
After turning on 41 layers when the 42th is turned on, the map no longer has updates.
The Legend component is updated but the map image don't.
To reproduce this:
In SheboyganAsp map create 45 copies of the layer Districts.

I don't know if this is the exact place to raise this problem.
I apologize if it is not.

Regards 
Jose

**Comment by jumpinjackie** [comment]
browser/mapguide/mapguide-react-layout version?

**Comment by joseaaz** [comment]
The last one v0.12.8

**Comment by jumpinjackie** [comment]
And what browser?

**Comment by joseaaz** [comment]
I tested in this browsers:
Google Chrome version 79.0.3945.88
Google Chrome version  81.0.4016.0
Internet Explorer 11 Version 11.0.165
Firefox version 71.0

**Comment by joseaaz** [comment]
Problem solved.
At some point the requests to mapagent.fcgi got bigger than the maxquerystringlength defined in iis.

Adding to the web.config of mapagent.fcgi the following keys solved the problem:
```
<system.web>
<httpRuntime maxQueryStringLength="65536" maxUrlLength="65536"/>
</system.web>
<system.webServer>
 <security>
 <requestFiltering>
 <requestLimits maxQueryString="65536"/>
 </requestFiltering>
</security>
</system.webServer>
```

So sorry Jackie for wasting your time, wasn't a mapguide-react viewer problem.

**Comment by jumpinjackie** [comment]
Makes sense. Glad you found your solution.
