### ISSUE TITLE
Overview map bug

### ISSUE THREAD

**Issue by loshhilov** [jumpinjackie/mapguide-react-layout#1074]
MapGuide OS 3.1.2.9484 x64
Ubuntu 14.04 Server x86_64
WebTier - MapGuide Apache
mapguide-react-layout 0.13-master
Firefox 72.0.1 x64, Chrome 79.0.3945.117 x64, IE 11.0.9600.19572

1. Go to 'External Base Layers' and enable any not-NONE layer.

2.1 Click on button 'Overview Map'.
2.2 See empty main map.

3.1 Drag map.
3.2 Map content show, overview map content hide.

4. Map flickering/performance loss is also observed when dragging/zooming.
5. The same application in mapguide-react-layout-0.12.8 works fine.

**Comment by jumpinjackie** [comment]
The update to OpenLayers 6 must've changed/broke something
