### ISSUE TITLE
Mouse wheel zooming artefact

### ISSUE THREAD

**Issue by loshhilov** [jumpinjackie/mapguide-react-layout#1128]
mapguide-react-layout v0.13 (since 2020-02-12)
Appeared after update to OpenLayers 6.2.0
The zoom direction is changed spontaneously and the panorama is shifted.
Especially noticeable when the mouse wheel rotates slowly.

**Comment by jumpinjackie** [comment]
I'm having trouble "visualizing" this problem. Could you post a gif screen recording of the before and after? You can use a tool like [screentogif](https://www.screentogif.com/) to record gifs.

**Comment by jumpinjackie** [comment]
Also, OL 6.2.0 did change mouse wheel behavior. From [release notes](https://github.com/openlayers/openlayers/releases/tag/v6.2.0)

> Mousewheel zooming now brings the same user experience as trackpad zooming. One click on the wheel no longer means a jump of a whole zoom level. Instead, depending on the speed of moving the wheel, the user has fine-grained control over zoom increments/decrements.

Is this what you're referring to? If so, then it's by OL's design and there's nothing I can do about that.

**Comment by loshhilov** [comment]
In the "light" sample project (Sheboygan) this problem was not seen either.
This is probably due to changes in OL 6.2.0.
If so, can close the problem.
Try to make for you gif from my real app.

**Comment by loshhilov** [comment]
2020-02-11 Step wheel zoom - OK:
![gut](https://user-images.githubusercontent.com/25501987/74733346-2f773880-525d-11ea-84ec-3cd89a063091.gif)

2020-02-12 with OL 6.2.0 - step zooming issue (back zoom and shift):
![bad](https://user-images.githubusercontent.com/25501987/74733528-9137a280-525d-11ea-9136-c06c0b798dc5.gif)

**Comment by loshhilov** [comment]
accidentally closed :)

**Comment by loshhilov** [comment]
Additional note: the breakdown occurred after these changes:
#git pull
...
 * [new branch]      feature-ol612 -> origin/feature-ol612
Updating fa39b57..4d9910d
Fast-forward
		docs_dev/content/RELEASE_NOTES.md    |   2 +-
		package.json                         |  14 ++++-----
		src/api/bootstrap.ts                 |  60 ++++++++++++++++++-------------------
		src/api/ol-factory.ts                |   5 ++--
		src/components/map-viewer-base.tsx   |   8 +----
		src/components/map-viewer-context.ts |   6 ++--
		viewer/sidebar.html                  |   2 +-
		yarn.lock                            | 312 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------------------------------
 8 files changed, 204 insertions(+), 205 deletions(-)

**Comment by loshhilov** [comment]
Issue fixed in mapguide-react-layout v0.13.2
Thank you very much!
