### ISSUE TITLE
Tile maps not correct 13.1 version

### ISSUE THREAD

**Issue by cserve** [jumpinjackie/mapguide-react-layout#1160]
Hi,

Problem: If I use a map that contains tiles, the map does not look good. 
The tiles are not in the right place.

The version 13.0 it was correct. See the different:
13.1:
![Tile map in 13 0 (correct)](https://user-images.githubusercontent.com/63050752/78247188-ba00b800-74ea-11ea-807b-aec4b196c575.png)
13.0:
![Tile map in 13 1 (incorrect)](https://user-images.githubusercontent.com/63050752/78247193-bb31e500-74ea-11ea-947c-d4c1aa254a7a.png)

I tried different EPSG systems, but not work.
**If I dont use Tiles, there is no any problem!!!!**

**My environment is:**
1. MapGuide
  * Version: 3.1.2
  * OS: Windows server 2016
  * WebTier configuration (IIS/Apache): Apache

2. mapguide-react-layout version: 13.1

**Comment by jumpinjackie** [comment]
I am confused as to what I'm looking at.

Firstly, there is no `13.0` and `13.1` releases. I assume you are referring to `0.13.0` and `0.13.1`.

Now going by that assumption, I don't know how/why you're using `0.13.0` because that release was immediately pulled and replaced with `0.13.1` a few minutes later when I found a critical map switching bug.

Please clarify the correct versions you are referring to.

Secondly, could you attach a copy of the Map Definition? I need an idea of the layer structure and coordinate systems you're working with

**Comment by cserve** [comment]
Hi,

Sorry the wrong versions name. I was careless.
**Of course we use the 0.13.1 versions.** Today we installed the latest environment with this: npm install --save mapguide-react-layout. 
(viewer folder copied to the appropriate location)
We made a video for you to show the problem.
But of course, we can attach the project too: Sidebar_EOV_TEST.mgp

We use EPSG:23700 coordinate system, but we tired another EPSG system too.

Here is the video link:  https://autode.sk/2R41E5a 

Best Regards, R.
[Sidebar_EOV_TEST.zip](https://github.com/jumpinjackie/mapguide-react-layout/files/4421753/Sidebar_EOV_TEST.zip)

**Comment by jumpinjackie** [comment]
Thank you very much for providing the test data and your very informative video!

Will that video link expire? I tried to download a local copy of that video with no luck.

**Comment by cserve** [comment]
Hi!

Here is the video ZIP file:

[Sidebar_teszt.zip](https://github.com/jumpinjackie/mapguide-react-layout/files/4421875/Sidebar_teszt.zip)

Best Regards, R.

**Comment by jumpinjackie** [comment]
Thanks for the video. I can confirm on my machine that the same problem happens for tiled maps. This is more than enough for me to work with. Cheers.

**Comment by jumpinjackie** [comment]
The 0.13.2 release will have this fix

**Comment by cserve** [comment]
Hi Jackie!


We successfully tested ! Perfect! **Thank you very much!** 
Best Regards! cserve
