### ISSUE TITLE
  initialElementVisibility dont work for taskpane

### ISSUE THREAD

**Issue by VolkerDr** [jumpinjackie/mapguide-react-layout#1205]
In v013.2 (aqua.html) I get
Invariant Violation: update(): $merge expects a target of type 'object'; got undefined
for
initialElementVisibility: {
                    taskpane: false,
                    legend: false,
                    selection: false
                },
without
taskpane: false
it works

_Originally posted by @VolkerDr in https://github.com/jumpinjackie/mapguide-react-layout/issues/246#issuecomment-673020659_

**Comment by jumpinjackie** [comment]
Try this build: https://ci.appveyor.com/api/buildjobs/hcaaeur9li5go0r7/artifacts/viewer.zip
