### ISSUE TITLE
bug in the legend.  When a group is selected in the legend and you move the cursor legend  the grouping  mark goes back to its default.

### ISSUE THREAD

**Issue by motipit** [jumpinjackie/mapguide-react-layout#1257]
# IMPORTANT! Please read this first

Issues in this repository concern only the viewer. **Do not submit bug reports concerning the MapGuide Server, FDO or isses in any other web mapping server or services**. Use the appropriate issue trackers for reporting such issues because this repo is not for that!

**Describe the bug**

**What is your environment?**
1. MapGuide Installation
  * Version:
  * OS:
  * WebTier configuration (IIS/Apache):
2. mapguide-react-layout version:

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots/Browser DevTools output**
Does your browser devtools (F12) show any console/network errors at the time the problem occurs or is there any visual indicators of the problem?

Include relevant output/screenshots here

**Comment by motipit** [comment]
IN Flexible Layouts  aqua  v0.13

**Comment by jumpinjackie** [comment]
I've made these issue bug templates so that you can and should be as descriptive as possible about this bug, in particular steps for reproduction, affected MG version/configuration and and any useful screenshots/gifs.

You have made little effort thus far to do any of this, so I will not be paying much attention to this bug until you have filled in this information.

**Comment by motipit** [comment]
Thanks for the fast repaly :)

MapGuide Installation: MapGuide Open Source 3.1.2
Version: 3.1.2
OS:winsowes server 2019
WebTier configuration (IIS/Apache): IIS
mapguide-react-layout version: v0.13
Steps to reproduce the behavior:

Bug number 1:
In Flexible Layouts react aqua v0.13
In the legend select a group  
Move the cursor in the map
See legend 
The grouping check mark is not selected anymore
Expected behavior: The grouping check mark should be stay selected
See Relevant video


Bug number 2:
In Flexible Layouts react aqua v0.13
In the old mapguide fusion this code worked ok.
At runtime through the code in the server I turn on the layer I want by:
layer.SetVisible(true);
map.Save()
After this command I use command from javascript:
reloadMap function  Fusion.getWidgetById('Map').reloadMap();
In the map We can see the layer but in the legend it is not have a check mark. 
The same problem when you add new layer in runtime you it does not appear in the legend.
Expected behavior: 
In the map the layer in the legend wil have a check mark. 
Adding a new layer at runtime will appear in the legend.

https://user-images.githubusercontent.com/9548674/116393521-67e3b080-a82a-11eb-9e1a-13e8d821a505.mp4

**Comment by jumpinjackie** [comment]
Ok! That's much better and informative! I'll take a look when I have some time.

**Comment by noambrand** [comment]
Dear jumpinjackie , 
We need your urgent help on this subject to meet our project goals. 
How can we persuade you to make it a priority?  We don't knew how to do this ourselves.  The emphasis is on Bug number 2.
Your response will be greatly appreciated.

**Comment by noambrand** [comment]
Thanks, you are the best!
