### ISSUE TITLE
Feature request-Window control of size and position at runtime

### ISSUE THREAD

**Issue by noambrand** [jumpinjackie/mapguide-react-layout#1258]
Dear jumpinjackie , 
Your React solution is wonderful and highly appreciated :) 
When a window opens we can't control its size like we did in Fusion, I mean fitting its horizontal and vertical dimensions and position on screen at runtime. 
It opens too small and the user has to manually adjust its size and position every time.
See Relevant video

Flexible Layouts react aqua v0.13
MapGuide Installation: MapGuide Open Source 3.1.2
Version: 3.1.2
OS:winsowes server 2019
WebTier configuration (IIS/Apache): IIS
mapguide-react-layout version: v0.13

https://user-images.githubusercontent.com/60847897/116440927-9fb61c80-a859-11eb-9ce0-754b0e5f9ca3.mp4

**Comment by jumpinjackie** [comment]
Modal size/position will now be persisted and honored if re-opened, as demonstrated in this video.

https://github.com/jumpinjackie/mapguide-react-layout/assets/563860/10a88091-161d-48d0-ab32-64ec129fe831

The modal display dispatchable actions should also honor initial size and position (if no previous modal
