### ISSUE TITLE
MG-React.v0.14.5 - Basic Layout isn't display

### ISSUE THREAD

**Issue by nimcnaan** [jumpinjackie/mapguide-react-layout#1374]
1. MapGuide 3.1.2, On windows.os & IIS + Client.OS' win 11
2. On Any web browser
3. Call - https://[myserverip]/mapguide/viewer/sidebar.html?resource=Library://Samples/Sheboygan/Layouts/SheboyganAsp.WebLayout

**Expected behavior**
We expected to see the maplayout.

**Screenshots/Browser DevTools output**

![browser-screean](https://user-images.githubusercontent.com/41572971/154017390-f226cf6b-bf0c-4fbd-b57c-613fb4b5354d.png)
![DevTool-Screenshot](https://user-images.githubusercontent.com/41572971/154017391-a398bd5e-eaf1-45a0-b977-f6b3cfb7f446.png)

**Comment by jumpinjackie** [comment]
Confirmed. Investigating a fix.

**Comment by jumpinjackie** [comment]
Problem is with the viewer init with WebLayouts. Does not happen with ApplicationDefinitions.

**Comment by nimcnaan** [comment]
U' right. Please check my next req.
