### ISSUE TITLE
Viewer Options - Base Layers opacity 

### ISSUE THREAD

**Issue by nimcnaan** [jumpinjackie/mapguide-react-layout#1426]
Hi jack,
Is there a way to add a separate-opacity-control for map's BaseLayers ?

If such a feature is important, we can offer funding this feature.
Any answer will be appreciated

**This feature is often requested by our users**
A feature of this kind can help to display more "clear" infrastructures map over an aerial layer, for example.
once the Arial or any other background layer is stored as a baselayer. 

**The solution can be**
Adding an opacity-slide control for  the "<TileSetSource>" section.
See the attached picture.
![baselayersopacity](https://user-images.githubusercontent.com/41572971/202493920-53eb03f0-d83d-4913-a9b5-d91bf8bd31bf.png)

**Comment by jumpinjackie** [comment]
Shouldn't be difficult
