### ISSUE TITLE
ZoomPrevious & ZoomNext  command not working

### ISSUE THREAD

**Issue by nimcnaan** [jumpinjackie/mapguide-react-layout#1438]
**Is your feature request related to a problem? Please describe.**
ZoomPrevious & ZoomNext  commands do not work, in any react-template layout.

**Describe the solution you'd like**
I would like those commands to work as they use to, in the previous version.

**Comment by jumpinjackie** [comment]
Cannot reproduce. The only strange thing I have observed is that a zoom to initial extents action pushes 2 views to the navigation stack instead of 1, but that's not enough of a "bug" to try and fix right now.

**Comment by nimcnaan** [comment]
Solved by changing the command to none Capital letters. Thanks

בתאריך יום ד׳, 31 במאי 2023, 18:39, מאת Jackie Ng ***@***.***
