### ISSUE TITLE
Shift-and-click to add/remove selections do not work.

### ISSUE THREAD

**Issue by prnell** [jumpinjackie/mapguide-react-layout#1444]
@jumpinjackie 
As an end user of the viewer I want to be able to change my selection by using the SHIFT-click method to add to the selected features and also to remove selections from the selected features so that I can control the selection set better.

**What is your environment?**
React viewer on MGOS 4

**To Reproduce**
Hold the shift key in and click on multiple features

**Expected behavior**
If the clicked feature is not selected I expect the feature to be added to the selection
If the clicked feature is already selected I select that feature's selection to be removed

**Comment by jumpinjackie** [comment]
Shift to add is now working.

Shift to remove is not. Will investigate later.
