### ISSUE TITLE
Support loading a Map Definition that links to an XYZ tileset

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#1461]
MGOS 4.0 lifts the restriction that a Map Definition must reference an non-XYZ tileset. However attempting to house this Map Def in a WebLayout or ApplicationDefinition and loading that into the react viewer fails because our viewer init logic has not been updated to check the underlying tile set provider type.

For this to work we need to do the following:

 1. Make a `v4.0.0` `CREATERUNTIMEMAP` request if we're talking to a MGOS 4.0 server
 2. Update our OL tiled layer factory logic to:
   a. Check the new `TileSetProvider` property in the v4 response
   b. If it is `XYZ`, instead of making a OL tiled layer with MG tile access scheme, make a OL XYZ layer instead

**Comment by jnelopenspatial** [comment]
On Maestro 6.0m12 When adding a XYZ or MVT tileset as a linked tileset receive a message
![0c370f31-0864-41f0-a7e3-ba4aeffc19d8](https://github.com/jumpinjackie/mapguide-react-layout/assets/113658605/d6e8c04a-47ee-4b44-82d8-92d1472ee6ba)
The tileset works as an external but need as a linked for attribute queries

**Comment by jnelopenspatial** [comment]
When adding a tileset to a mapdefinition we get the following error
![12ce6395-020a-45bb-950c-38d8959b650b](https://github.com/jumpinjackie/mapguide-react-layout/assets/113658605/fb08da7c-27b5-4e72-b243-2e8f03b2fb24)
When the same tileset is used as an external (Generic) )XYZ layer the data is visible in mapguide as well as QGIS
I can also confirm that its possible to add other vendor XYZ tilesets as (Generic) )XYZ layers and the data is visible in mapguide
