### ISSUE TITLE
No auto adjust on Layers Pane when using expand / collapse

### ISSUE THREAD

**Issue by WHendriksOpenspatial** [jumpinjackie/mapguide-react-layout#1484]
# IMPORTANT! Please read this first

Issues in this repository concern only the viewer. **Do not submit bug reports concerning the MapGuide Server, FDO or isses in any other web mapping server or services**. Use the appropriate issue trackers for reporting such issues because this repo is not for that!

**Describe the bug**
When opening Layers pane the list of layers (collapsed) display correctly within the pane layout:

![image](https://github.com/jumpinjackie/mapguide-react-layout/assets/135314014/fcdc5a12-3755-4a89-ba21-5600db8ac4d6)

However as soon as you expand a few Layers past the limits of the layers pane then the pane does not auto adjust or generate a scroll bar:

![image](https://github.com/jumpinjackie/mapguide-react-layout/assets/135314014/ab5bb7d8-b363-4c93-afe5-14cc3279b20b)

and has to be done manually:

![image](https://github.com/jumpinjackie/mapguide-react-layout/assets/135314014/14ae2781-3f89-41fe-af23-a27604d30dd1)

**What is your environment?**
1. MapGuide Installation
  * Version: 4.0
  * OS: Windows Server 2022
  * WebTier configuration (IIS/Apache): IIS
2. mapguide-react-layout version:

**To Reproduce**
Please see description above

**Expected behavior**
Please see description above

**Screenshots/Browser DevTools output**
Does your browser devtools (F12) show any console/network errors at the time the problem occurs or is there any visual indicators of the problem? No errors

**Comment by jumpinjackie** [comment]
I don't recognise the look of this window frame from any of our default viewer templates.

Is this a custom viewer template component? If so you're responsible for how to handle oversized legend content. In that case some solutions you can use are:

-  Put a `overflowY: auto` CSS style on the window frame "container" so over-sized legend content will present scrollbars on the window frame body.
-  Use a `ResizeObserver` to monitor for DOM element size changes on the legend content and adjust the window frame dimensions accordingly.

**Comment by WHendriksOpenspatial** [comment]
Thank you for those solutions. It did fix the issue we were having.
