### ISSUE TITLE
access getCurrentExtent() function from the taskpane ?

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#162]
Hi, 
How to access getCurrentExtent() function from the taskpane ?

I was trying to get NormalizedBox ( as like in QuickPlot taskpane)  values using getCurrentExtent()  for one of my taskpane. 
is there any way to access this in the content ( taskpane ).

-Sai

**Comment by jumpinjackie** [comment]
The IMapViewer API interface is now accessible from task pane content via `parent.parent.GetViewerInterface()`

I've added a demo page, that you can set up an InvokeURL command to point to the URL of this page `http://servername/mapguide/your_react_viewer_virtual_dir/examples/taskpane/viewerapi.html`

And in that demo page is an example of how to get the current extent

https://github.com/jumpinjackie/mapguide-react-layout/blob/master/viewer/examples/taskpane/viewerapi.html#L18

This will be available in the 0.9 release, or if you want to try this right now grab the bleeding edge `viewer.zip` from the [AppVeyor build artifacts page](https://ci.appveyor.com/project/jumpinjackie/mapguide-react-layout/build/artifacts)

**Comment by saivaradula** [comment]
Jackie:
this is very helpful. 
Thanks,
