### ISSUE TITLE
Cross Origin Resource Sharing (CORS)!

### ISSUE THREAD

**Issue by joseaaz** [jumpinjackie/mapguide-react-layout#174]
Initializing a Map using Coordinate system code 27493 or 3763 I get the error:
An error occurred during startup 
Unable to get property 'getExtent' of undefined or null reference
Stack Trace
•TypeError: Unable to get property 'getExtent' of undefined or null reference
• at E.createResolutionConstraint_ (http://localhost/viewer/viewer/dist/viewer.js:1:424471)
• at E (http://localhost/viewer/viewer/dist/viewer.js:1:415933)
• at t (http://localhost/viewer/viewer/dist/viewer.js:1:1159371)
• at t.prototype.initLayerSet (http://localhost/viewer/viewer/dist/viewer.js:1:1162927)
• at e.prototype.componentDidMount (http://localhost/viewer/viewer/dist/viewer.js:1:493860)
• at t.prototype.notifyAll (http://localhost/viewer/viewer/dist/viewer.js:1:434427)
• at d.close (http://localhost/viewer/viewer/dist/viewer.js:1:1010499)
• at r.closeAll (http://localhost/viewer/viewer/dist/viewer.js:1:174251)
• at r.perform (http://localhost/viewer/viewer/dist/viewer.js:1:173749)
• at r.perform (http://localhost/viewer/viewer/dist/viewer.js:1:173667)

Analising the network requests there is this information:

SEC7118: XMLHttpRequest for http://epsg.io/?format=json&q=27493 required **Cross Origin Resource Sharing (CORS).**
or
SEC7118: XMLHttpRequest for http://epsg.io/?format=json&q=3763  required **Cross Origin Resource Sharing (CORS).**

I think the problem is related. How is this corrected?

Regards

José Azevedo

**Comment by jumpinjackie** [comment]
Did the response headers for that request have `Access-Control-Allow-Origin: *`?

**Comment by jumpinjackie** [comment]
To help me reproduce, could you point me to any freely available portugese spatial data that I can easily set up a FeatureSource/LayerDefinition/MapDefinition/WebLayout to test with?

**Comment by joseaaz** [comment]
Hi.
I'm not sure the problem is related to Cross Origin Resource.

You can find a freely available portuguese spatial data at:
http://mapas.dgterritorio.pt/ows/caop/continente?service=wms&request=getcapabilities

I created the following web.config:
<?xml version="1.0"?>
<configuration>
 <system.webServer>
    <modules runAllManagedModulesForAllRequests="true"></modules>
   <httpProtocol>
     <customHeaders>
          <add name="Access-Control-Allow-Origin" value="*" />
          <add name="Access-Control-Allow-Headers" value="Content-Type" />
          <add name="Access-Control-Allow-Methods" value="GET,POST,PUT,DELETE,OPTIONS" />
         <add name="Access-Control-Allow-Credentials" value="true" />
        </customHeaders>
   </httpProtocol>
    <handlers>
        <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
        <remove name="OPTIONSVerbHandler" />
        <remove name="TRACEVerbHandler" />
        <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
        </handlers> 
 </system.webServer>  
  <system.web>
    <compilation debug="true" targetFramework="4.0"/>
  </system.web>

**Comment by joseaaz** [comment]
Hi.
Problem solved by editing index.html and adding the following code before viewer.mount:
 MapGuide.Externals.proj4.defs("EPSG:3763", "+proj=tmerc +lat_0=39.66825833333333 +lon_0=-8.133108333333334 +k=1 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs");

Thanks.
José Azevedo

**Comment by jumpinjackie** [comment]
Re-opening because I am seeing this error too. I think it's a timing issue where the map is being created before the projection from epsg.io has been registered

**Comment by TENsaga** [comment]
Hey there, sounds like we're experiencing a similar issue, using the custom mapguide container. The site is hosted on the same server as mapguide, we're using masked URL from a round robin pool that sends the request to one of a few servers, for example: "http://genericurl" which resolves to our IIS mapguide site. If you go directly to http://servername/mapguidesitename it resolves. Using version 0.10.0

```
An error occurred during startup
Blocked a frame with origin "http://servername" from accessing a cross-origin frame.
```

I've tried putting cors headers in all the IIS web.config locations. Seems to happen directly after returning the layout:

```
const layoutEl = getLayout(layout);
if (layoutEl) {
   console.log('returning layout');
   return layoutEl();
```

We see the loading page above this. Any thoughts on which direction we should go in?

**Comment by TENsaga** [comment]
Still digging, not sure if this helps:

![Rejected Promise](https://imgur.com/a/M6QZt)
