### ISSUE TITLE
Advanced Options in QuickPlot

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#188]
Hello, 

I am not able to get or activate the advanced options in the QuickPlot of viewer. In Fusion Mapguide,
Quickplot has the advanced option upon enabling which would have the bounding box as shown in the screenshot.

Where as in Quickplot in Viewer, advanced option check box is availiable but no action is replicated on checking it. 

Help or Suggestion would a great  help.

- Sai
![screenshot1](https://cloud.githubusercontent.com/assets/22417624/24652697/6bf34892-1950-11e7-9dcf-701596f60391.png)

**Comment by jumpinjackie** [comment]
The box capturer is not yet implemented for this version of the QuickPlot

**Comment by jumpinjackie** [comment]
The next release will have the map capture box. The only difference is that rotation will be controlled through a numerical slider in the Quick Plot UI

**Comment by saivaradula** [comment]
Jackie:
This capture box is good., but how can I implement it in customized quick plot widget.
Its working fine in default quick plot widget, 

- Sai
