### ISSUE TITLE
Process to enable External Base Maps other than OSM in React Viewer

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#189]
How to add external base maps in react viewer.

As of now, it is showing only OpenStreetMaps of Kind "OSM". I would like to add Google maps Street,, Google Maps Satellite and Bing Maps..

Please let me know where to make entries to enable Google Maps, Bing Maps.

Reference: As I found the below code in aqua.html.

 viewer.mount(el, {
                layout: "aqua",
                externalBaseLayers: [
                    { name: "OpenStreetMap", kind: "OSM" },
                    { name: "Stamen - Toner", kind: "Stamen", visible: true, options: { layer: "toner" } },
                    { name: "Stamen - Watercolor", kind: "Stamen", options: { layer: "watercolor" } }
                ],
                agent: {
                    uri: "../mapagent/mapagent.fcgi"
                }
            });

- Sai

**Comment by jumpinjackie** [comment]
OpenLayers does not support Google Maps, so neither will this viewer.

Bing support can be added by modifying (https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/components/external-layer-factory.ts) to check for a kind of `BingMaps` and make a BingMaps source for it.

I'm happy to take a pull request on this

**Comment by saivaradula** [comment]
Hi Jackie:

Please take pull request on this.

thanks,
-Sai

**Comment by saivaradula** [comment]
Jackie:

It will be a help if you can expedite enabling Bing maps - Street, Satellite as it is pressing requirement from the customer.

Thanks,
Sai
