### ISSUE TITLE
Display Segment wise length for line measure, area in different units -  sqm, sqy, acres,hectares

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#192]
Hi Jackie,
We would like to modify measure in Task pane to display  
1. Segment wise length for line measure
2. Area in different units -  sq meters, sq yards, acres, hectares for polygon

Kindly expose the api to access and modify measure. 

Reference: The attached image which explains our requirement.

Thanks,
- Sai

![measure-segment length display-area in sqm sqy acres hect](https://cloud.githubusercontent.com/assets/22417624/24954536/72c1f0ee-1f9d-11e7-97c6-f27dcab32d2a.jpg)

**Comment by jumpinjackie** [comment]
I'm happy to port across the segment length display on the panel, but not the live display for the actual geometry as that is OpenLayers 2.x code that I am not certain we have the ability to replicate with current OpenLayers

**Comment by saivaradula** [comment]
Jackie:

Please port segment length display on the panel and with a different color for each segment in the geometry.

Thanks,
- Sai

**Comment by JBurkinshaw** [comment]
Hi Jackie,

Functionality similar to that outlined by Sai would also be very useful in an application we are developing to replace our Fusion based application:
- Allow different units of measurement, ideally through the `<Units>` element in the measure widget configuration.
- Segment length display.

Has any progress been made on either of these? Is there anything we can do to assist with their implementation?

Thanks,
Joe

**Comment by jumpinjackie** [comment]
@JBurkinshaw `<Units>` element support will eventually be covered through work on #239 but that is kind of blocked by the segment display, which I have not made any progress on. If you have an idea how the segment display could be implemented, I'm happy to accept a pull request.

**Comment by jumpinjackie** [comment]
@JBurkinshaw Your approach sounds solid. My only point of contention would be around pushing measurement segment state to the redux store vs state local to the Measure component.

Which really boils down to: Would there be possibly anything else in the entire application that would care about the fact that `[measurement is currently taking place and here's the measured segments]`? I don't really see that right now, so I think pushing this state to a redux store is overkill and measurement segments as component-local state instead for the immediate short term.

The other thing to be aware of is that your approach needs to also work in a multi-map manner. When we switch maps, we also need to be able to switch active measurements, overlays, etc related to those maps as well. MeasureContext has helped insulate the Measure component from this, so your approach should build on what MeasureContext provides.

**Comment by jumpinjackie** [comment]
Measure now shows segments, but only in geodesic mode and only for the current measurement.

![measure-segments](https://user-images.githubusercontent.com/563860/36353874-245fbd72-1520-11e8-993e-779833d70a5e.gif)
