### ISSUE TITLE
Print widget 

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#194]
Hello Jackie:

Please let us know how to enable Print functionality in React Viewer. 

Thanks,
-Sai

**Comment by jumpinjackie** [comment]
I have not ported over Print command/widget as it is somewhat redundant with QuickPlot. What case does QuickPlot not address?

**Comment by saivaradula** [comment]
Jackie:
I think you are right. QuickPlot is addressing print functionality.

- Sai
