### ISSUE TITLE
Viewer with Mapserver 2015

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#196]
Jackie:

It's not an issue, but a quick question.
Does the viewer support or work with MapServer 2015 MapGuide?

Thanks,
- Sai

**Comment by jumpinjackie** [comment]
What is the major.minor version returned by MapServer 2015? 

Is it 2.6? I think you might be one version off.

As per the readme:

>> MapGuide Open Source **3.0 or equivalent version** of Autodesk Infrastructure Map Server (and newer versions)
