### ISSUE TITLE
Selected Polygon Info 

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#202]
Jackie:

How can I get the details of the selected polygon or object into task pane, 
as like in Selection task pane.
For example, I just wanted to print table format of object No ( Plot No ) and Area.
In featureinfo, I can see the total area, but I want to display the object no with the area in the tabular format. 

Can you suggest the syntax or function names. 

- Sai

**Comment by saivaradula** [comment]
Jackie:

Please find the attached file, which would explain requirement of displaying selected features attributes such as area.

Thanks,
- Sai
![multipleselect](https://cloud.githubusercontent.com/assets/22417624/25263523/e33c2ede-267d-11e7-8101-455c6a2b57d7.png)

**Comment by jumpinjackie** [comment]
Unfortunately, the client-side selection data only carries the attributes part and not the actual geometry part. 

How are you doing this currently in Fusion?

**Comment by saivaradula** [comment]
Hello Jackie:
Please find the JavaScript code in Fusion, to get the attribute details.

var map = parent.Fusion.getMapByName(mapName);

if (map.hasSelection()) {
  map.getSelection(displaySelection);
}

function displaySelection(selection) {
  for (var i = 0; i < selection.getNumLayers(); i++) {
                var selectionLayer = selection.getLayer(i);
                var propNames = selectionLayer.getPropertyNames();
                for (var j = 0; j < selectionLayer.getNumElements(); j++) {
                    for (var k = 0; k < propNames.length; k++) {

                        if (propNames[k] == 'FeatId') {
                            FeatIds += selectionLayer.getElementValue(j, k) + ",";
                        }
                        if (propNames[k] == 'PLOT_NO') {
                            PlotNos += selectionLayer.getElementValue(j, k) + ", ";
                        }

                        if (propNames[k] == 'TOTAL_LMIS_AREA') {
                            strArea += selectionLayer.getElementValue(j, k) + ", ";
                            iArea = parseFloat(iArea) + parseFloat( selectionLayer.getElementValue(j, k) );
                        }
                    }
                }
            }
}

and finally displaying these values in a table. 
--------------------------------------------------------------------------

Even in React, We would like to display attribute data like Plot No, Plot Area and not Geometry attributes.

**Comment by jumpinjackie** [comment]
You can use the new selection handler API (#144) in your task pane content to listen for selection changes and write out the the HTML table with your plot feature attributes based on the selection object.

Rough code overview:

```

window.onload = function() {
     parent.parent.RegisterSelectionHandler(selectionHandler);
     console.log("Selection Listener installed. Remember to uninstall this handler when page unloads");
};

window.onunload = function() {
     parent.parent.UnregisterSelectionHandler(selectionHandler);
     console.log("Selection listener uninstalled");
};

var plotsLayer = "Plots"; //Fix to match the name of your actual plots layer

function selectionHandler(mapName, selection) {
            if (selection) {
                var layer = selection.SelectedFeatures.SelectedLayer.filter(function(l) { return l["@name"] == plotsLayer; })[0];
                if (layer) {
                    // TODO:
                    // Look up layer.LayerMetadata to determine the display names for
                    //   FeatId
                    //   PLOT_NO
                    //   TOTAL_LMIS_AREA
                    // Loop through layer.Feature array
                    // For each item
                    //   Find matching Name/Value pair in item.Property array based on the display names for your attributes
                    //   Write out the matching Value to a HTML table cell
                }
                console.log("Selection for (" + mapName + "):\n" + xml.replace(/</g, "&lt;").replace(/>/g, "&gt;\n"));
            } else {
                console.log("Selection for (" + mapName + ") is empty");
            }
        }

```

**Comment by saivaradula** [comment]
Thanks for the code.
Sai
