### ISSUE TITLE
Process to enable External Base Maps other than OSM in React Viewer#189

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#223]
Hi Jackie:
We are using Autodesk infrastructure map studio which does not have provision to enter API Key for Bing maps. 

Please, provide syntax for inserting Bing maps API key in ApplicaitonDefnition.xml

 Thanks,
Sai

**Comment by jumpinjackie** [comment]
It will be

```
<ApplicationDefinition>
    ...
    <Extension>
        <BingMapKey>YOUR_BING_MAPS_API_KEY</BingMapKey>
    </Extension>
</ApplicationDefinition>
```

**Comment by saivaradula** [comment]
Okay. thanks for the info Jackie.
One simple question, does viewer takes the ApplicationDefinition from Mapserver or does it has another path?

- Sai
