### ISSUE TITLE
Debug init.ts file for ExternalBaseLayers 

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#225]
Hello Jackie:

I have tried out all the instructions given in solution for #189 . However, I could not be able to view the BingMaps in external layer. 
I have also directly made some changes to init.ts file. But I could not find the BingMaps in the externalBaseLayers array.

Changes I have tried with init.ts.

```
case "VirtualEarth":
                        {
                            //HACK: De-arrayification of arbitrary extension elements
                            //is shallow (hence name/type is string[]). Do we bother to fix this?
                            const name = map.Extension.Options.name[0];
                            const type = map.Extension.Options.type[0];
                            const options: any = {};
                            let bAdd = true;
                            switch (type)
                            {
                                case "Aerial":
                                case "a":
                                    options.imagerySet = "Aerial";
                                    break;
                                case "AerialWithLabels":
                                    options.imagerySet = "AerialWithLabels";
                                    break;
                                case "Road":
                                    options.imagerySet = "Road";
                                    break;
                                default:
                                    bAdd = false;
                                    logger.warn(`Unknown bing maps layer type ${type}. Skipping this layer`);
                                    break;
                            }

                                /*if (appDef.Extension.BingMapKey) {
                                   options.key = appDef.Extension.BingMapKey;                                  
                                } else {
                                    bAdd = false;
                                    logger.warn(`A Bing Maps API key is required. Sign up for an API key at http://www.bingmapsportal.com/`);
                                 }*/

                                options.key = 'wvF72dWQDZJ4jpTpjZ7G~z55kvUbdD5U4NaqQ3fjHGQ~AqLF9Z9K2Qau4Si6bYiR1bZ2JeGpBn2uNYTAQiiVSgCw8tqfsLwJQMtZ86Pt8WtH';
                                //if (bAdd) {
                                    externalBaseLayers.push({
                                        name: name,
                                        kind: "BingMaps",
                                        options: options
                                    });
                                //}
                            }
                            break;
```

Can I debug the init.ts file. ? and How can I see the output ( if in case I put something as output )

Attached is the screenshot showing the external base layers ( default ) 
![external](https://cloud.githubusercontent.com/assets/22417624/25847943/d8c38518-34d5-11e7-939a-ecf723f2d7c5.png)

- Sai

**Comment by jumpinjackie** [comment]
For best dev/debugging experience you should be using Google Chrome with the following extensions:

 * [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en)
 * [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)

This is how I dev/debug.

I git clone this repo to a folder that I then create a virtual directory under the `mapguide/mapserver` virtual directory (eg. `http://localhost/mapguide/viewer`) and point it to the `viewer` directory of my git clone

Then I do the following:

 1. `yarn install`
 2. `yarn run watch:dev`

This will start webpack in watch mode with full debugging information.

I can then go to `http://localhost/mapguide/viewer/<my_template>.html?resource=<path_to_my_appdef_or_weblayout>`

When you fire up Chrome dev tools you should now see a `webpack://` node under the `Sources` tab where you can see all the TypeScript files

![2017-05-13 02_16_37-developer tools - http___localhost_mapguide_react_slate html_resource library___](https://cloud.githubusercontent.com/assets/563860/26007087/6518b3cc-3782-11e7-9991-f3a65b905586.png)

Then you can stick break points at the desired places, wait for the break points to hit and then you can start debugging the problem.

Now the beauty of webpack in watch mode is once you've identified the problem and need to make changes, you can make the required changes in the TypeScript source files and the moment you save, webpack will instantly re-compile affected source files in the background which you can then reload the browser afterwards and the new changes will kick in.
