### ISSUE TITLE
Make flyouts behave like their Fusion counterparts

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#244]
When you interact with Flyout menus in Fusion, there is a certain observable pattern:

- Toggling a flyout puts the whole viewer in a "Flyout is open" state
- Hovering the mouse into another flyout menu will close the current open flyout and toggle the flyout your mouse pointer is over.
- Clicking the active flyout menu button puts the viewer back in "Flyout is closed" state

We should try to preserve this behaviour.

**Comment by JBurkinshaw** [comment]
Has any progress been made on this? Currently a flyout will remain open until the user clicks the button which opened it again. It would be intuitive if flyouts close when the user clicks anywhere else in the application.

I have had a look at the code but it is not obvious to me how this can be configured.

**Comment by jumpinjackie** [comment]
No I have not yet had a chance to look at this. The key blocker is finding a reliable way to capture a [click outside the menu]
