### ISSUE TITLE
Disable selection, legend and task pane on map load and enable them later

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#246]
Hello Jackie:
We have closed selection, legend and task pane on initial load of the map, because of which the Selection, Legend and Task pane widgets are getting disabled and we are unable to use them after map load.

Please let us know the process to hide/close Selection, Legend and Task pane on the initial map load and enable them on click of Selection, Legend and Task pane buttons

Thanks,
- Sai

**Comment by jumpinjackie** [comment]
Is there a particular template you are referring to? I ask because for a template like `slate`, the selection, legend and task pane all physically reside in a (currently un-collapsible) sidebar.

**Comment by saivaradula** [comment]
I am using aqua and limegold.

**Comment by jumpinjackie** [comment]
Ok, I've got an idea how to do this.

I'll add support for a mount parameter that lets you define initial template element visibility, so it will look something like this:

```
var el = document.getElementById("map");
var viewer = new MapGuide.Application();
...
viewer.mount(el, {
   ...,
   initialElementVisibility: {
       taskPane: false,
       selection: false,
       legend: false
   }
});
```

Then you just modify your aqua and limegold templates (it appears you're already modifying these templates) to call `mount` just like above.

How does that sound?

**Comment by saivaradula** [comment]
Yes please,

**Comment by jumpinjackie** [comment]
Implementation checklist:

 - [ ] Add mount options support for `initialElementVisibility`
 - [ ] (ajax-viewer) Collpase sidebars if TaskPane/Selection/Legend are not visible
    - [ ] Also implies that we need to port across the panel togglers
 - [ ] (sidebar) Collapse sidebar if all TaskPane/Selection/Legend are not visible
 - [ ] (slate) Collapse the sidebar if all TaskPane/Selection/Legend are not visible
 - [ ] (maroon) Collapse the sidebar if all TaskPane/Selection/Legend are not visible
 - [ ] (limegold) Collapse the sidebar if all TaskPane/Selection/Legend are not visible
 - [ ] (turquoiseyellow) Collapse the sidebar if all TaskPane/Selection/Legend are not visible

**Comment by jumpinjackie** [comment]
As of 0.9.1 you should now be able to hide Legend/TaskPane/SelectionPanel through the `initialElementVisibility` mount option.

However, only the `aqua` and `sidebar` templates can practically take advantage of these new options as the other templates do not currently have a notion of a collapsible sidebar, which is what we'd collapse if Legend/TaskPane/SelectionPanel were all set to not be visible. Basically, you cannot hide *all* elements for these other templates, nor can you show all of them either.

**Comment by VolkerDr** [comment]
In v013.2 (aqua.html) I get
Invariant Violation: update(): $merge expects a target of type 'object'; got undefined
for
initialElementVisibility: {
                    taskpane: false,
                    legend: false,
                    selection: false
                },
without
taskpane: false
it works
