### ISSUE TITLE
Jumping ToolTip

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#251]
Hello Jackie:

I have a Tooltip with Tabs. 

The tooltip is displayed on mouse over of Parcel and when I move Pointer to a Tab on ToolTip, ToolTip is showing information of different Parcel.

Tooltip used to be stable when the pointer is moved from one tab to another tab in the earlier version of AIMS 2016 but in AIMS 2017 with react viewer, Tooltip is jumping.

Please view the action in the below URL.
URL: http://49.205.113.234/ada/viewer/web/viewmap.php

- Sai

**Comment by jumpinjackie** [comment]
Yep, I see your issue.

Interactive tooltip content is definitely something we need to have still working from Fusion.

**Comment by jumpinjackie** [comment]
I think I know what's happening.

It is sending tooltip requests while the mouse point is inside the tooltip content. Fusion doesn't do this.
