### ISSUE TITLE
Tooltip Not loading for Point

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#252]
Hello Jackie:

I am not able to get the tooltip to the point ( when mouseover ), but I am able to get ( loading ) tooltip for a polygon.

Sample Link: 
http://49.205.113.234/REGEN/viewer/aqua.html?resource=Library%3a%2f%2fREGEN%2fDATA%2fTEST%2fCENTRIOD.ApplicationDefinition

-Sai

**Comment by jumpinjackie** [comment]
It would be great if you could capture the `QUERYMAPFEATURES` tooltip request for an example point in both the react viewer and fusion viewer and compare the WKT `GEOMETRY` that is passed up for both and put the example geometries here.

**Comment by saivaradula** [comment]
Hello Jackie:

Tool tip is showing null in React viewer for point data. 

React Viewer:
http://49.205.113.234/REGEN/viewer/aqua.html?resource=Library%3a%2f%2fREGEN%2fDATA%2fTEST%2fCENTRIOD.ApplicationDefinition

Response:
{"FeatureInformation":{"FeatureSet":[{"@xmlns:xsi":["http://www.w3.org/2001/XMLSchema-instance"],"@xsi
:noNamespaceSchemaLocation":["FeatureSet-1.0.0.xsd"]}],"Hyperlink":null,"InlineSelectionImage":null,"SelectedFeatures"
:null,"Tooltip":null}}



Fusion 
http://49.205.113.234/mapserver2017/fusion/templates/mapguide/aqua/index.html?ApplicationDefinition=Library%3a%2f%2fREGEN%2fDATA%2fTEST%2fCENTRIOD.ApplicationDefinition

Response:

{"FeatureInformation":{"FeatureSet":[{"@xmlns:xsi":["http://www.w3.org/2001/XMLSchema-instance"],"@xsi
:noNamespaceSchemaLocation":["FeatureSet-1.0.0.xsd"],"Layer":[{"@id":["f2c0bb44-5671-11e7-8000-00e04c0113ac"
],"Class":[{"@id":["Schema1:RIICO_IA_CENTROID"],"ID":["mq0FAAAAAAA="]}]}]}],"Hyperlink":null,"InlineSelectionImage"
:null,"SelectedFeatures":null,"Tooltip":[" IANAME  = Lalsot"]}}

-Sai

**Comment by jumpinjackie** [comment]
Did you happen to capture the request and parameters?

**Comment by saivaradula** [comment]
![fusion_get_params](https://user-images.githubusercontent.com/22417624/27828575-6d2db036-60da-11e7-9ebd-30222e48f023.png)
![viewer_post_params](https://user-images.githubusercontent.com/22417624/27828576-6d2dccba-60da-11e7-9983-f8ba05bfb50b.png)

Jackie:
Please find the images ( screenshots) with the parameters .

 -Sai

**Comment by jumpinjackie** [comment]
Thank you for the screenshots. I see what's happening. It's not supposed to send the actual geographic point from the mouse pointer, it's supposed to send a pixel-buffered polygon from that geographic point.
