### ISSUE TITLE
Zoom to Selection Xml

### ISSUE THREAD

**Issue by a1astair** [jumpinjackie/mapguide-react-layout#260]
What is the proper way to zoom to selectionXml after using the `viewer.setSelectionXml()` function? As that does select the object on the map but does not zoom. Would you have to use the zoomToExtent() api call and pass in the bounds of the selectedXml?

Also to add on to this, is there a way to find a layer id if you have the name and value for a Property in that layer? It looks like each Feature has an array of Properties. Is there a way to search Layers for these Properties and then grab the specific feature that matches?

**Comment by jumpinjackie** [comment]
The 3rd argument of [viewer.setSelectionXml](https://jumpinjackie.github.io/mapguide-react-layout/apidoc_npm/interfaces/_api_common_.imapviewer.html#setselectionxml) is a callback that accepts the full selection model you get back, from there you can build up the zoom bounding box by looping through the BBOXes of all the selected features in the selection model.

You can see an example of how to do this [here](https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/containers/viewer-shim.tsx#L371). Ignore the preceding `TODO` comment, it is actually done.

Regarding your second question, not a the moment as I have not yet provided APIs to access the layer/group structure through the `IMapViewer` interface.

**Comment by a1astair** [comment]
Perfect thank you so much @jumpinjackie! Really appreciate all the feedback.

**Comment by a1astair** [comment]
In my case I needed to zoom to a constant level on a feature so I replaced 
```
if (bounds) {
  const bw = olExtent.getWidth(bounds);
  const bh = olExtent.getHeight(bounds);
  if (bw > 0 && bh > 0) { //Don't zoom if we get 0 bounds. Cruncing bounds from selected points would do this.
    const view = viewer.getViewForExtent(bounds);
    this.parent.ZoomToView(view.x, view.y, view.scale, true);
  }
}
```
with this 
```
if (bounds) {
  const view = viewer.getViewForExtent(bounds);
  viewer.zoomToView(view.x, view.y, zoomConstant);
}
```
as I was getting 0 for the Height and Width checks but was getting a value for the bounds so I still wanted to zoom to that feature with an amount based on a Constant I brought in

**Comment by jumpinjackie** [comment]
To answer the other question, the next release (0.10) the `ApplicationViewModel` class that is represented as the top-level `MapGuide.Application` now has a `getState()` method which returns a snapshot of the global redux application state. In this state is the full runtime map JSON with full layer and group structure.
