### ISSUE TITLE
Differing Selection Xml ID's

### ISSUE THREAD

**Issue by a1astair** [jumpinjackie/mapguide-react-layout#263]
It looks like the ids for the selectionXml differ from the layout and the id's I make from the mapguide .net code. For Example when I generate some Selection Xml with some c# code like so 
```
MgSelection selection = new MgSelection(map);
selection.AddFeatures(layer, featureReader, 0);
string selXml = selection.ToXml();
```

I get some Xml with an id value like `<ID>MzUzOTY4MDMA</ID>`
Which is what was used to set selection Xml and zoom in the older layout that used the original Fusion API.

This new layout seems to have ID's with differing values and I cannot get the xml from the .net code to match up with these new values.

If I have a FeatureSet with an ID such as `QldEUzIyMjMxMzE1AA==` it seems to have a completely different format. Is there any way I can match the ids from the .net code to the id's on the new layout? As I am trying to generate the xml on the backend and then pass it through.

Any pointers would be greatly appreciated, Thanks!

**Comment by jumpinjackie** [comment]
That ... doesn't make sense.

Generation of selection XML ids from features is deterministic. Given a particular feature, you'll always be getting the same selection XML id out of its identity properties. Whether through the mapagent, or the .net/PHP/Java wrapper to the MapGuide API, you should always be getting the same value out.

Are you sure you didn't pick some other id by mistake?

**Comment by a1astair** [comment]
Ok thanks for the feedback I will double check my ID's!
