### ISSUE TITLE
Dynamic Filter for Layer

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#274]
Hello Jackie:

I would like to apply a dynamic filter to layer using PHP on the load using Mapguide or Viewer
How can I approach for dynamic filtering of the layer without duplicating the layer.

- Sai

**Comment by jumpinjackie** [comment]
I don't think that's even possible. MgLayer filters are immutable. You don't really have a choice but to duplicate the original layer with the new filter.
