### ISSUE TITLE
Primary Icon Issue with v0.9.1

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#281]
Hello Jackie:

I have an issue, when I load the viewer.js file from the version 0.9.1 ( latest release ), my primary icons which are clickable ( or opens the task pane ) are not working. Only Measure icon is able to open the task pane for measure widget. 

I have general Search Icon, which should open search task pane, but which I click it, its not responding or not able to open task pane. 

Can you suggest if I am doing wrong while upgrading to new release. 

- Sai

**Comment by jumpinjackie** [comment]
Do you have a demo link showing the problem?

**Comment by saivaradula** [comment]
Jackie:
Please use this link.

http://49.205.113.234/REGEN/viewer/aqua.html?resource=Library%3a%2f%2fREGEN%2fLAYOUT%2fREGEN3.ApplicationDefinition

- Sai

**Comment by saivaradula** [comment]
Jackie:
is it something that issue [#276](https://github.com/jumpinjackie/mapguide-react-layout/issues/276) can resolve ??

- Sai

**Comment by jumpinjackie** [comment]
Yes, it should be.

I checked by taking a copy of your AppDef, fixing up the map back to Sheboygan and loading it in my local viewer with aqua template and I am seeing lots of 404s referring to your specific icons.

**Comment by jumpinjackie** [comment]
Closing. Please re-open if the issue still exists as of 0.9.5.
