### ISSUE TITLE
Add application-specific reducers to Redux 

### ISSUE THREAD

**Issue by Rastamafugg** [jumpinjackie/mapguide-react-layout#318]
Our company is developing a product using the mapguide-react-layout framework, but we are having problems figuring out how to add our own reducers to the Redux store managed by mapguide-react-layout.  Presently we are having to store application state inside our components (which is a big Redux no-no) as a workaround.  Other redux-based frameworks, such as Apollo, provide options to pass in an outside store object into the framework instead of initializing it internally specifically for this purpose.

Is there an option that we are missing, or can there be an similar option provided (or alternatively some sort of initialization function exposed that allows us to pass in an array of reducers into the mapguide-react-layout before the combineReducers() function is called?

**Comment by jumpinjackie** [comment]
I'd have to research this idea.

Initial thought is something akin to how we're doing the [template reducer](https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/reducers/template.ts), a proxy reducer function for a certain branch that you can forward to the real reducer function that you can register beforehand.

... or I can see how apollo does it. [Is this the apollo you're referring to?](https://github.com/apollographql/react-apollo)

How are you using mapguide-react-layout? Standard viewer.js bundle? npm module? Raw git clone/fork w/ modifications? I gather it must be either git clone/fork or npm module.

**Comment by Rastamafugg** [comment]
That's a related library. Here's the [main project website](http://dev.apollodata.com/).

It looks like in their recent update, they've changed things so that they have an ApolloClient object that has functions for generating and returning middleware and reducer object to an application and leave it up to the application to setup the Redux store, middleware, and reducers as the application sees fit.

So an example of a store setup looks something like this (my example is using a modified [react-boilerplate](https://www.reactboilerplate.com/) template):

`
/**
 * Create the store with asynchronously loaded reducers
 */

import { createStore, applyMiddleware, compose } from 'redux';
import { fromJS } from 'immutable';
import { routerMiddleware } from 'react-router-redux';
import createSagaMiddleware from 'redux-saga';
import createReducer from './reducers';

const sagaMiddleware = createSagaMiddleware();

export default function configureStore(initialState = {}, history, apolloClient) {
  // Create the store with three middlewares
  // 1. sagaMiddleware: Makes redux-sagas work
  // 2. routerMiddleware: Syncs the location/URL path to the state
  // 3. apolloClient.middleware: Middleware for Apollo Client
  const middlewares = [
    sagaMiddleware,
    routerMiddleware(history),
    apolloClient.middleware(),
  ];

  const enhancers = [
    applyMiddleware(...middlewares),
  ];

  // If Redux DevTools Extension is installed use it, otherwise use Redux compose
  /* eslint-disable no-underscore-dangle */
  const composeEnhancers =
    process.env.NODE_ENV !== 'production' &&
    typeof window === 'object' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ : compose;
  /* eslint-enable */

  const store = createStore(
    createReducer({
      apollo: apolloClient.reducer(),
    }),
    fromJS(initialState),
    composeEnhancers(...enhancers)
  );

  // Extensions
  store.runSaga = sagaMiddleware.run;
  store.asyncReducers = {}; // Async reducer registry

  // Make reducers hot reloadable, see http://mxs.is/googmo
  /* istanbul ignore next */
  if (module.hot) {
    module.hot.accept('./reducers', () => {
      import('./reducers').then((reducerModule) => {
        const createReducers = reducerModule.default;
        const nextReducers = createReducers(store.asyncReducers);

        store.replaceReducer(nextReducers);
      });
    });
  }

  return store;
}
`

**Comment by Rastamafugg** [comment]
To answer your other question, we're working with a modified copy of your mapguide-react-layout-example as our project code base

**Comment by jumpinjackie** [comment]
Ok, this is my current game-plan to allow for custom reducers.

You will need to subclass `ApplicationViewModel` and override:

 * `getExtraReducers` (to provide your own custom reducers)
 * `getExtraInitialState` (to provide your own initial state)

The `mount` method will object spread whatever your overridden methods return into the base initial state and root reducer set before initializing the redux store with them

Then in your webpack entry point, you would export your subclass instead of `ApplicationViewModel`. This way, the entry point template HTML files will be instantiating and mounting from your subclass instead of the default `ApplicationViewModel` and will be set up with the custom reducers and any custom initial state you specify.

How that that sound?

**Comment by Rastamafugg** [comment]
Sounds promising, but wouldn't the reducers be responsible for returning their own initial state objects on initialization?  I'm not clear what the getExtraInitialState function's purpose is.

**Comment by jumpinjackie** [comment]
It's basically to satisfy the `preloadedState` parameter of [createStore](http://redux.js.org/docs/api/createStore.html)

We're calling `createStore` [here](https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/store/configure-store.ts#L13)

**Comment by Rastamafugg** [comment]
Ok, do you have an estimate on when this might get added in to the library?

**Comment by jumpinjackie** [comment]
It's already in. I need to test this in the context of the npm module to verify what we want to do is possible.

**Comment by Rastamafugg** [comment]
Just wanted to let you know this is working as intended for us.  Thanks!
