### ISSUE TITLE
Support for external WMS layers

### ISSUE THREAD

**Issue by SoroTrestal** [jumpinjackie/mapguide-react-layout#324]
Hi Jackie, is there an option available in the viewer to serve WMS layers directly (i.e. add them to open layers as a source instead of adding them in MapGuide as a raster layer).

**Comment by jumpinjackie** [comment]
Not at the moment, but this is actually a useful feature to have.

**Comment by jumpinjackie** [comment]
Moving back milestone

**Comment by jumpinjackie** [comment]
Good news! I've got a basic UI in place for adding custom layers. 

![add-wms-layer](https://user-images.githubusercontent.com/563860/31556703-c9c134f6-b091-11e7-8a0e-2d885d6c351f.gif)

Initial focus will be for adding WMS (and possibly WFS) layers, which we'll then expand to cover additional vector and raster formats supported by OpenLayers

**Comment by jumpinjackie** [comment]
How to access this feature:

Add an InvokeURL command that has a URL of `component://AddManageLayers`

Example XML fragment to put into your Fusion widget set:

```
    <Widget xsi:type="UiWidgetType">
      <Name>AddManageLayers</Name>
      <Type>InvokeURL</Type>
      <Location />
      <Extension>
        <Target>TaskPane</Target>
        <Url>component://AddManageLayers</Url>
        <DisableIfSelectionEmpty>false</DisableIfSelectionEmpty>
        <AdditionalParameter />
      </Extension>
      <ImageUrl />
      <ImageClass>layer_add</ImageClass>
      <Label>Add/Manage Layers</Label>
      <Tooltip />
      <StatusText />
      <Disabled>false</Disabled>
    </Widget>
```
