### ISSUE TITLE
Busy indicator without zoom control in Ajax viewer template

### ISSUE THREAD

**Issue by SoroTrestal** [jumpinjackie/mapguide-react-layout#325]
Hi Jacky I noticed when I turn of the zoom control in the Ajax viewer template there is no indicator that the map is loading, or am I missing something?

Regards

**Comment by jumpinjackie** [comment]
This is because the only loading indicator that's available is embedded in the Navigator (zoom control) that you have turned off.

I need to bring across the original AJAX viewer indicator or look at a load indicator that will always be present regardless of template used.

**Comment by jumpinjackie** [comment]
By a load indicator that will always be present, I mean something like this example:

http://openlayers.org/en/latest/examples/image-load-events.html?q=load

**Comment by SoroTrestal** [comment]
Ok thanks Jackie

**Comment by jumpinjackie** [comment]
I've implemented a persistent load indicator that will be present in any layout. It's based on the OL example I previously linked.

![load-indicator](https://user-images.githubusercontent.com/563860/29572031-60855038-879e-11e7-939d-47ee7b1e230d.gif)
