### ISSUE TITLE
Override default selection panel

### ISSUE THREAD

**Issue by Rastamafugg** [jumpinjackie/mapguide-react-layout#331]
Is there a correct way to override the selection panel component? We want to be able to replace the default selection panel with a custom one that calls a REST API to load additional attribute data around a selection when a selection is made in the MapGuide interface.  We're working off of a modified version of the GitHub repository, and the only way I can see how to do it is to modify the selection-panel.tsx file directly, which seems wrong.

**Comment by jumpinjackie** [comment]
#36 partially (or maybe even fully) addresses this. I think when I made that task the idea was to allow the body of the Selection Panel to be delegated to a custom render function (passed from props) if the default selected attribute display is not desirable. Your custom render function can render a custom selected feature display component that does your REST API calls when it mounts or receives new props.

Would this address your issue?

**Comment by Rastamafugg** [comment]
Sounds like something like this would work.  Is this still outstanding functionality, or has this been implemented?

**Comment by jumpinjackie** [comment]
This has been implemented and will be in the 0.10 release

**Comment by Rastamafugg** [comment]
I'm having problems getting this working with the latest code base.  I'm assuming I need to call registerComponentFactory with a customized version of the SelectionPanel that gets passed a custom renderer factory, but my initial test is generating an erro on initialization:

```
Uncaught (in promise) TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (DOMLazyTree.js:69)
    at Object.dangerouslyReplaceNodeWithMarkup (Danger.js:40)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (DOMChildrenOperations.js:124)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (ReactCompositeComponent.js:783)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:773)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:723)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:644)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:546)
    at Object.receiveComponent (ReactReconciler.js:124)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:753)
```

Here is the relevant code:

```
import * as React from "react";
import { FeatureProperty } from "../api/contracts/query";
import { tr as xlate} from "../api/i18n";
import { registerComponentFactory, DefaultComponentNames } from "../api/registry/component";
import { ISelectedFeatureProps } from "../components/selection-panel";
import SelectionPanelContainer from "../containers/selection-panel";

//Custom components
import SearchComponent from "./components/search";

const TestSelectedFeature = (props: ISelectedFeatureProps) => {
    const { selectedFeature, selectedLayer, locale } = props;
    const featureProps = [] as FeatureProperty[];
    for (const lp of selectedLayer.Property) {
        const matches = selectedFeature.Property.filter(fp => fp.Name === lp.DisplayName);
        if (matches.length === 1) {
            featureProps.push(matches[0]);
        }
    }
    return <table className="selection-panel-property-grid pt-table pt-condensed pt-bordered">
        <h1>TestSelectedFeature Renderer</h1>
        <thead>
        <tr>
            <th>{xlate("SELECTION_PROPERTY", locale)}</th>
            <th>{xlate("SELECTION_VALUE", locale)}</th>
        </tr>
        </thead>
        <tbody>
        {featureProps.map(prop => {
            return <tr key={prop.Name}>
                <td>{prop.Name}</td>
                <td>{prop.Value}</td>
            </tr>;
        })}
        </tbody>
    </table>;
};

function selectedFeatureRendererFactory(props: any) {
    let { feat, meta, locale } = props;
    return (<TestSelectedFeature selectedFeature={feat} selectedLayer={meta} locale={locale} />);
}

function selectionPanelContainerFactory(props: any) {
    props.selectedFeatureRenderer = selectedFeatureRendererFactory;
    return (<SelectionPanelContainer {...props} />);
}

export function registerCustomComponents() {
    //Register custom components
    registerComponentFactory(DefaultComponentNames.SelectionPanel, selectionPanelContainerFactory);
    registerComponentFactory("SearchComponent", () => <SearchComponent />);
}
```

**Comment by Rastamafugg** [comment]
Ok, I fixed a couple of bugs and it's working.  But is this the correct way to set a custom selection panel renderer?  It seems a little awkward having to re-register the Selection Panel factory, but I couldn't find a way to just register the renderer.

**Comment by jumpinjackie** [comment]
The signature of the selection panel renderer is supposed to match a React stateless functional component.

So you should be able to just say directly `<SelectionPanelContainer selectedFeatureRenderer={TestSelectedFeature} />`

Secondly, you only need to register custom components via `registerComponentFactory` if you intend to:

- Render this component by name via a `<PlaceholderComponent>`
- Render this component into a designated container (TaskPane, Modal Dialog, etc) via invoking a URL that follows the `component://` pseudo-URI scheme

In the case of the a custom selection panel, assuming this is an application-wide customization, the intended way to use this is to locate the layout template components that need a custom selection panel and modify its `<PlaceholderComponent>` reference like so:

```
import { TestSelectedFeature } from ???;

...

<PlaceholderComponent id={DefaultComponentNames.SelectionPanel} locale={locale} componentProps={{ selectedFeatureRenderer: TestSelectedFeature }} />
```
