### ISSUE TITLE
Highlighting selected features

### ISSUE THREAD

**Issue by Rastamafugg** [jumpinjackie/mapguide-react-layout#348]
I'm trying to get the [highlighting of a selected feature](https://themapguyde.blogspot.ca/2017/08/react-ing-to-need-for-modern-mapguide_28.html) functionality working, but I'm stuck on the step after the initial queryMapFeatures call. Here is the code I have so far:

```
let selectionXml: FeatureSet = {  Layer: [{"@id": `${selectionObj.layerId}`, Class: {"@id": `${selectionObj.classId}`, ID: [`${selectionObj.featureId}`]}}]};

const options: Request.IQueryMapFeaturesOptions = {
    mapname: activeMapName,
    session: sessionId,
    requestdata: Request.QueryFeaturesSet.InlineSelection,
    layerattributefilter: 0,
    featurefilter: this.buildSelectionXml(selectionXml),
    persist: 0,
};
getViewer().queryMapFeatures(
    options, 
    (response: Query.QueryMapFeaturesResponse) => {
        console.log(response.SelectedFeatures);
    }, 
    (error) => {
        console.log(error);
    }
);
```

When my success function gets called the response object contains my featurefilter selection set and an InlineSelectionImage object with Content and MimeType attributes.  I gather this is the image overlay that will provide the feature highlighting on the map, but how do I get it to display on the screen?

**Comment by jumpinjackie** [comment]
There's a new `showSelectedFeature` redux action in `actions/map` that does all of this for you.

Just pass it the mapName, layer id and feature index.

The `SelectionPanel` component has a new `onShowSelectedFeature` callback that will get passed the layer id and feature index. Just subscribe a handler to this and dispatch the `showSelectedFeature` in the handler.

**Comment by Rastamafugg** [comment]
Thanks, that did the job!  It looks like the highlight polygon doesn't get re-rendered on map zoom, though.  Is this planned as a feature enhancement?  Otherwise, I guess I'll have to detect the zoom and re-fire the highlight code manually.

**Comment by jumpinjackie** [comment]
I originally thought about implementing auto re-rendering on zoom in/out on the worry that the ol static image source that I house the sub-selection image in wouldn't auto scale the image on zoom in/out. 

This was not the case, and the fact that even as a stretched out blob, the sub-selection can still easily be picked out, so I sort of left it as it is.
