### ISSUE TITLE
Unable to open task pane - in Latest version

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#385]
Hello Jackie:

I have updated to latest version of MapGuide react layout, now, I am not able to get taskpane opened when clicked on the icons.
Here's the screenshot.  - Can you please suggest

![issue_primary_icons](https://user-images.githubusercontent.com/22417624/31484438-ede59a4c-af4d-11e7-811e-35c9ea35536c.png)

**Comment by jumpinjackie** [comment]
There is not enough information here.

 - Do you see any javascript errors?
 - Do you see a `Fusion/SET_TASK_PANE_VISIBILITY` action being dispatched?
 - Is the button a reference to the built-in `showTaskPane` command?

**Comment by saivaradula** [comment]
Hello Jackie:
I could not see any javascript issues in the console.
Fusion/SET_TASK_PANE_VISIBILITY - Not sure about this action, if so, where can I see this. and Moreover, there is nothing happening when I click on the icon. 
As for now, the Only Measure is working, and nothing else. 

yes, the button has a reference to showtaskpane - like, in aims studio 2017, we are referencing this icon to open taskpane and content from a php page is pulled. 

- Sai

**Comment by saivaradula** [comment]
This issue is happening from version - 0.9.1. Its working fine in 0.9.0

**Comment by jumpinjackie** [comment]
Do you have a demo link (just so I can see this for myself)?

**Comment by saivaradula** [comment]
Jackie:

Here is the link:

http://183.83.218.176/REGEN/viewer/aqua.html?resource=Library%3a%2f%2fREGEN%2fLAYOUT%2fREGEN3.ApplicationDefinition

- Sai

**Comment by jumpinjackie** [comment]
Thanks for the link. I see the problem. For commands that aren't opening the task pane, their `<Widget>` definitions in the Application Definition do not have a `<Target>` set on them.

The viewer currently assumes such commands to be commands that open in a specific frame instead of a new window (which fusion does).

I'll change the logic to assume a new window if no target is set. Until then, try explicitly setting the `<Target>` on your commands that are not opening to `TaskPane` or `NewWindow`.

**Comment by saivaradula** [comment]
Jackie:
I have set target as new window. Can you make it availiable to open when its new window. 

- Sai

**Comment by jumpinjackie** [comment]
Correction, you need to set `<Target>` to `InvokeUrlWindow` or `TaskPane`. 

`NewWindow` is for AJAX viewer Invoke URL commands.

Anything else (even if empty) the viewer will assume is a frame reference. After 5abb6fc empty references are assumed to be treated as `InvokeUrlWindow`
