### ISSUE TITLE
Capture Box in Quick Plot for customised taskpane

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#400]
Jackie:
This capture box is good,  but how can I implement it in customized quick plot widget.
Its working fine in default quick plot widget,

I would like to use in the customized Task pane. 
Can you be able to make the functions available? 
- Sai

**Comment by jumpinjackie** [comment]
The key parts to this involve using the layer management aspects of `IMapViewer` and using the OL object factory (also provided by `IMapViewer` through its `getOLFactory` method)

Reminder: If you're working a non-react, browser global script context (eg. Task Pane content) you can obtain an instance of `IMapViewer` through the global `GetViewerInterface()` API.

You basically want to replicate the `MapCapturerContext` class [that I've implemented](https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/containers/map-capturer-context.ts) for use with the Quick Plot. This class is not currently available in a browser global script context, so you have to replicate it yourself. Where I'm `new`-ing OL classes directly in `MapCapturerContext` you use the OL factory to create equivalent layers/interactions/etc.

Then the process of rendering a capture box is to:

1. Obtain an `IMapViewer` instance.
2. Instantiate or obtain your MapCapturerContext clone instance using the obtained `IMapViewer`
3. [activate](https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/containers/map-capturer-context.ts#L103) your context passing in a callback that will receive updated box coordinates as the user rotates and drags the box around.
4. If you need to update the current box with new paper size, scale or rotation, call [updateBox](https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/containers/map-capturer-context.ts#L63) with the new data. Your callback will receive updated box coordiantes.
5. When you are finished and want to remove the capture box, call [deactivate](https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/containers/map-capturer-context.ts#L110)

**Comment by saivaradula** [comment]
Hi Jackie:

I am working on the Task Pane to get the capture box. I have initialized iMapViewer using javascript code below:
 viewer = parent.GetViewerInterface();

from now, i tried to obtain MapCapturerContext using the code
var mcc =  viewer.MapCapturerContext(viewer, mapName, 4);
But, I am getting the error MapCapturerContext is not defined. 
Can you help me out with the issue. 

Thanks,
Sai

**Comment by jumpinjackie** [comment]
MapCapturerContext is not part of the public API that you can get at from Task Pane content (it's why I'm currently suggesting you replicate the whole class in plain JavaScript)

**Comment by saivaradula** [comment]
Okay, 
I understood. I will try to put on plain javascript in new class. 

- Sai
