### ISSUE TITLE
Point Transform

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#424]
Hello Jackie:

When I click on the map to get point ( as in redline to make a point on the map ), I am getting the x and y co-ordinates but I want the points to be sent to google map to view nearest POIs. 
Before sending  I have to convert the points to decimal degree  
( example like from 7689439.800113952, 3566432.4256 to something to this 17.4501582, 78.366700 ).

I have used the below function, but this is giving an error.

var b = new OpenLayers.Projection('GEOGCS["LL84",DATUM["WGS84",SPHEROID["WGS84",6378137.000,298.25722293]],PRIMEM["Greenwich",0],UNIT["Degree",0.01745329251994]]');

Error:
OpenLayers.Projection is not a constructor

Do we have any function converting the points?  

- Thanks,
Sai

**Comment by jumpinjackie** [comment]
Does this work for you?

```
var from = "EPSG:XXXX";
var to = "EPSG:YYYY";
var viewer = GetViewerInterface();
var factory = viewer.getOLFactory();
var txPt = factory.transformCoordinate([ x, y ], from, to);
//Transformed coordinates are - x = txPt[0], y = txPt[1]
```
Fill in `XXXX` and `YYYY` for EPSG codes as required.

On a side-note, regarding projections: Don't bother with WKT, just use EPSG codes where possible.

**Comment by saivaradula** [comment]
Thanks for the solution. 
I will with above functions. 

- sai

**Comment by saivaradula** [comment]
It gave me the following error:
TypeError: t is null in viewer.js file.

I am using  
var from = "EPSG:LL84";
        var to = "EPSG:WGS84";

![error](https://user-images.githubusercontent.com/22417624/32546185-3abea69a-c4a4-11e7-9631-bd0fb2e21449.png)

- Sai

**Comment by jumpinjackie** [comment]
EPSG codes are numeric

LL84 is `EPSG:4326`
WGS84.PseudoMercator is `EPSG:3857`

**Comment by saivaradula** [comment]
Jackie: amazing. 
Thanks for the solution. Its perfect now. 

- Sai
