### ISSUE TITLE
Directions on the Map with Two points

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#439]
Hello Jackie:

Let's call it as question rather than issue, 
I have a task pane in which User will be picking up two points (point A, point B )  by clicking on the map and background is open street map, now if user clicks on the button get direction, is there any possibility ( or API calls ) that user get the direction from A to B on the map.

Attaching an image. 
![direction](https://user-images.githubusercontent.com/22417624/33001180-4c81b7a0-cdd2-11e7-96fa-1203d90fe6b1.png)

- Sai

**Comment by jumpinjackie** [comment]
You need to find a routing API that provides geographic elements to its routing waypoints. You would then convert these waypoints to equivalent OL geometry and load it into a "routing results" OL vector layer so it can be shown on the map.

I don't know what routing APIs out there will give you such information, but this is what you should look for in a routing API.

**Comment by saivaradula** [comment]
Thank you for the suggestion. I have found a api which provides the routing waypoints.
I am trying to convert and put on the map.

Thanks
- Sai
