### ISSUE TITLE
Base Layer Map control

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#443]
Jackie:

Can you suggest?
I have MapGuide application map showing data ( polygons ) and I have chosen open street maps as base maps.
is there any possibility that I can get the control ( or object ) over the open street map ( or base map of my application ) - from the task pane or directly,  to perform actions like adding a layer or plotting a point on this map ( or layer on this map ).

if possible, how can I get control or object for this map.

**Comment by jumpinjackie** [comment]
This is now possible with the new experimental subscriber API in the upcoming 0.13 release as demonstrate by this task pane content example: https://github.com/jumpinjackie/mapguide-react-layout/blob/master/viewer/examples/taskpane/subscriberapi.html
