### ISSUE TITLE
Styles or Properties of Redline

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#449]
Hello Jackie:

I am printing or drawing a line string using Redline. Do we have any options or features where we can change the styles of the line ( for example color or the line string or thickness ) - may be using viewer.

- Sai

**Comment by jumpinjackie** [comment]
Are you using the fusion redline widget? This is what mapguide-react-layout also uses. 

In this case, the redlining UI already has options for controlling layer style of drawn redlines.

If you just want to change the default style, just modify `YOURFUSIONINSTALL/widgets/Redline/classes/defaultstyle.php` and change the style settings within to your desired default values.
