### ISSUE TITLE
Flyout Zoom Controls are Behind the Map

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#45]
Sidebar flyout controls for zoom appear to be behind the map and unclickable

**Comment by jumpinjackie** [comment]
Are you referring to the "Zoom" flyout menu on the main vertical toolbar of the sidebar template? 

That's a [known issue](https://github.com/jumpinjackie/mapguide-react-layout/blob/master/KNOWN_ISSUES.md). Need to find a way to make flyouts "break out" of its parent.

**Comment by Crispin-at-Linknode** [comment]
Yes, that issue exactly. I scanned the issues list for something similar.
It looks like a z-order thing - but if it was that simple in sure you would have tried it!

Linknode
121 George Street, Glasgow G1 1RD
t: +44 141 559 6170
m: +44 7703 442 059
www.linknode.co.uk

Sent from my Windows Phone, please excuse some brief formatting.
________________________________
