### ISSUE TITLE
Initial Map Load without Task and Selection pane

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#465]
Hello Jackie:

I have been closing the selection pane and task pane on initial map load and hence set timeout for loading or showing the loaded map.

so, initially, its slowing the loading performance.  
is there any way that initially only selection pane and task pane are not loaded. 

- Sai

**Comment by saivaradula** [comment]
Please find the URL below:

http://183.83.218.176/REGEN/viewer/aqua.html?resource=Library%3a%2f%2fREGEN%2fLAYOUT%2fREGEN3.ApplicationDefinition

- Sai

**Comment by jumpinjackie** [comment]
Have you tried modifying the `viewer.mount()` call to specify `initialElementVisibility`? (https://github.com/jumpinjackie/mapguide-react-layout/issues/246#issuecomment-308135849)

**Comment by saivaradula** [comment]
Yes, I did.
I am using aqua template, is it applicable to this template.

- Sai

**Comment by saivaradula** [comment]
Hello Jackie:
is the closing of initial task and selection pane is applicable to the aqua template?
Everything looks fine except I am explicitly closing the initial panes. 

- Sai

**Comment by jumpinjackie** [comment]
@saivaradula I finally had time to take a look at this. You claim that you modified the `viewer.mount()` call to specify `initialElementVisibility` in response to my question.

Yet when I load up your demo site and look at the HTML source, I do not see this setting applied.

![missing](https://user-images.githubusercontent.com/563860/36030109-01c7d3b2-0dfa-11e8-951b-870ba8edb6aa.png)
