### ISSUE TITLE
All the Base Layers will be on initially regardless of the map setting

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-react-layout#476]
Hi Jackie,

I am using v0.10.0 with AIMS 2017 (v3.1.1.4601), and all the base layers will be on initially.

Although, I set all the base layers will not be displayed initially, and shown in the legend that they're all unchecked.

Is this a known issue going to be fixed?

Thanks!

**Comment by jumpinjackie** [comment]
Ok, I see it. I thought you meant base layers like Bing/OSM/etc. It's the other kind of base layers

**Comment by RenoSun** [comment]
I just tested, and it worked! v0.11.1
