### ISSUE TITLE
Widget flyout drop down menu automatically close

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-react-layout#479]
Hi Jackie,

I like the fact I can click on the flyout, and view the drop down menu of the widgets.

However, it will be nice if we can only display one flyout at once.

![image](https://user-images.githubusercontent.com/5566783/34587570-ae4e66b4-f15d-11e7-81a0-ef6194ea70b1.png)

Some users may prefer to have many flayouts open, and manually close the unneeded ones.

Thoughts?

Thanks!

**Comment by jumpinjackie** [comment]
Basically you want #244

**Comment by jumpinjackie** [comment]
Flyouts are now mutually exclusive. If you open any flyout, any other open flyouts are closed. 

It's not 1:1 with how it behaves in Fusion (getting auto-flyout on mouseover of a flyout menu is more difficult), but is better than what we currently have.
