### ISSUE TITLE
Print and Save Map widgets are displayed with Error Icons

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-react-layout#480]
Hi Jackie,

I am able to use Quick Plot and Invoke URL Custom Print Widgets, but see there are error icons for both Print and Save Map widgets.

![image](https://user-images.githubusercontent.com/5566783/34588237-c0e48350-f160-11e7-822d-981afae8d08f.png)

Is this a know issue? and are there widgets going to be supported?

Thanks!

**Comment by jumpinjackie** [comment]
I originally though about wanting to reach 100% parity with all the widgets Fusion supports (#243)

But I've come to realize that some components:

 * Do not make any sense at all in mapguide-react-layout`
 * Are somewhat redundant.

I think Print is pretty redundant (QuickPlot does it and much more). Still on the fence about SaveMap

**Comment by RenoSun** [comment]
I agree with Print is pretty redundant, and I always use QuickPlot.
