### ISSUE TITLE
Support partial application state in the URL (was: Enhancement Requests)

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-react-layout#481]
Hi Jackie,

Here are the features that I always wish MapGuide/AIMS Fusion will provide by default:

1. Layers/Layers Groups turn on/off history stored with URL parameters. Therefore, the users may share the URL with each other, and refresh the web page without turn on/off whole bunch layers or layer groups (including base layers) again.
ex: hg=Cadastral,Zoning&hl=Roads&sl=QBIncorporationHistory,QBZoning

2.  Current map extent can be stored with URL parameters, and keep being updated when the user zoom in/out, panning around the map.
ex: curextent=-13854516.504702,6334618.2438916,-13853592.691556,6335079.2547184

3.  Auto Select and Zoom to the extent of selection by using URL parameters. 
https://mapguide.wordpress.com/2013/06/11/autodesk-infrastructure-map-server-auto-zoom-on-load/

ex: layer=QBParcels&attribute=QBID&attvalue=1012,1013

I just think these are really handy features to have. or please just let me know what codes should I modify with mapguide-react-layout.

Please let me know your thoughts.

Thank you for building mapguide-react-layout!

**Comment by jumpinjackie** [comment]
We basically need to integrate a router component (or a clean wrapper over `window.history` that takes care of browser quirks) where we can encode application state into the URL at any time and to be able to read said state from it. The problem here is that there's so many to choose from, bundle size is of concern.

**Comment by RenoSun** [comment]
I am no professional in founding the best application state encoder, but hope you or others may provide decent suggestion.

Something like [react-url-query](https://www.npmjs.com/package/react-url-query)?

**Comment by jumpinjackie** [comment]
Hey, you're good at this library hunting thing! I'll take a look at this.

**Comment by jumpinjackie** [comment]
Ok, `react-url-query` appears to be a winner. We now have partial application state being pushed to the URL.

Observe the `scale` parameter in the URL auto-updating upon change of view and view state being restored in the gif below.

![url-state](https://user-images.githubusercontent.com/563860/35809239-2ae59142-0adc-11e8-81c2-54847498d716.gif)

Currently this pushes to the URL:
 * Session ID
 * Current View (x/y/scale)

This doesn't work at the moment in IE. But I'm not overly concerned there. Not everything can be made to work in IE.

**Comment by jumpinjackie** [comment]
The question of how best to persist selection state in the URL we'll move off to the next milestone

**Comment by jumpinjackie** [comment]
For 0.12 the missing piece of application state (selection set) is now persisted between browser reloads.

We just stash a copy of the selection set into local storage on every selection action and restore it along with the other runtime map state on viewer startup if the browser reloaded.
