### ISSUE TITLE
Right-click Menu not showing any widgets

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-react-layout#482]
Hi Jackie,

The Right-click menu has appeared to be empty... I remembered it works with previous version.

![image](https://user-images.githubusercontent.com/5566783/34589441-800ce278-f165-11e7-8fb6-1f486ad3bd36.png)

Only the AJAX viewer will display the right click widgets...with Basic Layout only.

I am using v0.10.0 with AIMS 2017 (v3.1.1.4601).

Thanks!

**Comment by jumpinjackie** [comment]
The viewer is hard-coded to look for a UI item container named `MapContextMenu`

![containers](https://user-images.githubusercontent.com/563860/35858267-f6cd508e-0b8f-11e8-805b-021697c5bb8e.png)

If no such container exists, nothing is loaded into the viewer context menu.

**Comment by jumpinjackie** [comment]
Okay, in terms of any work to do on my side, I'll push a viewer init warning (similar to external base layer mis-configuration warnings) if we can't find this UI item container, so you can at least visually see something is not right.

**Comment by jumpinjackie** [comment]
This is what you'll get now if you don't have the right context menu container name in your Flexible Layout

![Uploading nocontextmenu.png…]()
