### ISSUE TITLE
Applying Mutliple filter for Rest image

### ISSUE THREAD

**Issue by karunainfotech** [jumpinjackie/mapguide-react-layout#486]
Hello 
 I am able to generate the below image using rest api for mapguide.
http://183.83.218.176/regen/rest/index.php/data/district/82.png

I am able to filter polygon layer,  Can I get the image with multiple filters ( single point and polygon ).

- KK

**Comment by jumpinjackie** [comment]
This is not a mapguide-react-layout question. Use the mapguide-rest repository for such questions in the future. I'll answer your completely unrelated question just this one time.

The route `data/district/82.png` is a *single feature* access route, the route focuses on a single feature (In this case, a district with id = 82), and given the `.png` extension this basically renders the map with the `id = 82` district feature being the main focus.

What you are after is the *all features* access route which renders one or more features in a given representation based on a FDO filter or bounding box.

So in the map image case, you want to use this URL (use `.png` without any id in front of it)

`http://183.83.218.176/regen/rest/index.php/data/district/.png?filter=<your FDO filter>`

You can bring up the swagger UI for this configured RESTful data source to see what other APIs you can use with this URL:

http://183.83.218.176/regen/rest/index.php/data/district/doc/index.html
