### ISSUE TITLE
Couldn't load Aims 2017 flexible layouts

### ISSUE THREAD

**Issue by mimescua** [jumpinjackie/mapguide-react-layout#508]
Hi Mr. Jackie

I'm a little bit confused about using Aims 2017 flexible layouts. It results in a "An error occurred during startup / Attempted to load the following resource, but it was not found: Library://... .ApplicationDefinition".

Where do I apply the footnotes of the TEMPLATES.md page?  How do I author my Fusion Flexible Layouts?

I'm just starting with Mapguide, so, thanks in advance Mr Jackie.

![image](https://user-images.githubusercontent.com/4094190/35645672-975b78be-069a-11e8-87d8-71f5463e21a6.png)

**Comment by jumpinjackie** [comment]
Firstly, download [MapGuide Maestro](https://jumpinjackie.github.io/mapguide-maestro/)

Then let's go through the error one by one.

The error `Attempted to load the following resource, but it was not found: Library://AST/spatialnet.ApplicationDefinition` means exactly what it says.

The flexible layout resource (`Library://AST/spatialnet.ApplicationDefinition`) does not exist. How can you check? When you connect to your MapGuide Server in Maestro, you should be expecting to see your flexible layout here:

![spatialnet](https://user-images.githubusercontent.com/563860/35684685-c9a59a58-07bb-11e8-9710-4e0f86377526.png)

Secondly, how do you apply the footnotes in TEMPLATES.md?

When you open the Flexible Layout (aka. Application Definition) in Maestro, you basically need to make sure that in the Widgets section of the editor, that you have top-level containers with the required names specified in TEMPLATES.md

![flex_containers](https://user-images.githubusercontent.com/563860/35685140-f7fe0236-07bc-11e8-976a-94f3ed13fb15.png)

**Comment by mimescua** [comment]
My solution: change the name of my web layout (.ApplicationDefinition) and call it with the name of the PC instead of "localhost".

![image](https://user-images.githubusercontent.com/4094190/35834363-618f5216-0aa3-11e8-9bdd-51d5beaab04d.png)

*I considered all those facts you mention before, but for some reason I got that mistake over and over again. By the way, no matter how much I want to work with MG Maestro, it doesn't have an Oracle 12c FDO connector.
