### ISSUE TITLE
Vet Map Configuration 

### ISSUE THREAD

**Issue by karunainfotech** [jumpinjackie/mapguide-react-layout#510]
Hello Jackie,

We are tried to configure the  govhack-vet-provider-map  from repository path http://themapguyde.blogspot.in/search?q=vet

 i found few files are missing from repository . please fine the link below of Vet Map configuration in our server for the error details 
List of missing files i found 
1.  services folder in rest folder
2. Createmap.Json file

![vetmap](https://user-images.githubusercontent.com/34934938/35731882-60172f3e-083d-11e8-9d4d-feeae4193872.png)

**Comment by jumpinjackie** [comment]
The vet map is not a project that uses mapguide-react-layout
