### ISSUE TITLE
Task Bar Dropdown Options Hidden When Inital Task Pane URL is a PDF (in IE 11)

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#52]
When setting the initial task pane URL to a PDF, the "Task Bar" drop-down menu options are hidden and cannot be accessed when viewing in Internet Explorer.

MapGuide classic AJAX viewer works OK as this does not try and hover the menu above the content, but expands the menu section to move all content down.

Test: Win 7, x64

IE 11.0.35 - FAIL
Firefox 49.0 - OK
Opera 40.0 - OK
Chrome 53.0 - OK

**Comment by jumpinjackie** [comment]
I assume your PDF is viewing inline in IE? What PDF viewer plugin are you using? I have none so PDFs URLs are file download prompts for me in IE.

**Comment by jumpinjackie** [comment]
Okay, I see it. I tried a URL to a DWF in the Task Pane and the Autodesk Design Review plugin kicked in and now I see the flyout menu problem.

**Comment by Crispin-at-Linknode** [comment]
Yes, inline -- I just have Adobe "Acrobat Reader DC" installed which I guess registered itself with IE as an embedded reader.  It appears that Chrome/Opera and FF use their own built-in renderers as the UIs are subtuly different across the browsers.
I appreciate that may cause an edge-case problem for IE!

**Comment by jumpinjackie** [comment]
Just an extra data point: This happens with Fusion's task pane as well.

This is an annoying bug! There is a workaround involving sticking in a higher z-index iframe, but I have no idea how I can possibly retrofit the required markup into the Task Pane.
