### ISSUE TITLE
Split Polygon-How to draw lines with inputs as vertex, distance from vertex, angle

### ISSUE THREAD

**Issue by karunainfotech** [jumpinjackie/mapguide-react-layout#556]
Hi Jackie,

We would like to split a polygon using distance, angle from a vertex.

Pls let us know if mapguide api provides for this functionality.

Thanks
KK

**Comment by jumpinjackie** [comment]
No, it does not.

For future reference, only use this repository for issues/questions related to the mapguide-react-layout viewer. Use the mapguide-users mailing list for MapGuide Server/General questions.
