### ISSUE TITLE
Issues with pan/zoom/finger gestures on iOS

### ISSUE THREAD

**Issue by TENsaga** [jumpinjackie/mapguide-react-layout#568]
We're having issues with our map on iOS 11.x Chrome & Safari. Users cannot perform finger gestures to pan/zoom/rotate most of the time. Once in awhile the gesture will register but stop shortly after initiating. All of our Android devices seem to work. 

Any thoughts on why this is happening? It sounds [similar to this](https://stackoverflow.com/questions/39540515/google-maps-javascript-api-doesnt-respond-to-touch-events-in-ios-10)

Currently using mapguide-react-layout 0.10.0

Appreciate it.

**Comment by jumpinjackie** [comment]
Unfortunately I don't own a physical iOS device to test or verify this.

Since we're using OpenLayers, at a minimum let's verify that OL is not the culprit here. Do any of these [examples](https://openlayers.org/en/latest/examples/) work with touch?

**Comment by TENsaga** [comment]
All of those work without issue on our iOS devices.

Thanks for helping us look into this.

**Comment by TENsaga** [comment]
Hey @jumpinjackie, we managed to find a few additional iOS devices for testing. It looks like the iPad (iOS 10.3.3), and iPhone 8 (iOS 11.2.6) work in both browsers, but our iPhone 5s' (also iOS 11.2.6) do not.

I'm not exactly sure I understand why; possibly hardware related?
