### ISSUE TITLE
Does Map guide Open Source latest version Supports Oracle 12c 

### ISSUE THREAD

**Issue by karunainfotech** [jumpinjackie/mapguide-react-layout#575]
Hello Jackie:
As I am trying use Map guide Open source, I would like to know if latest version of Map guide Open Source Supports Oracle 12c database ?

Thanks,
KK

**Comment by jumpinjackie** [comment]
Not at the moment. The King Oracle provider is built against the 11g instant client SDK.

I may consider building the King Oracle provider against the Oracle 12c instant client SDK for the next major release (3.3) in mid-this-year.

**Comment by karunainfotech** [comment]
Thanks for the information Jackie.

**Comment by karunainfotech** [comment]
Jackie,
Please consider releasing Oracle 12c Provider for both Linux, Windows Versions of Map guide.

Thanks,
KK

**Comment by jumpinjackie** [comment]
I've posted experimental version of the King Oracle FDO provider with 12c support:

https://trac.osgeo.org/mapguide/wiki/Release/3.1.1/Notes#Patches
