### ISSUE TITLE
Tooltips Missing

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#59]
I am not seeing any tooltips in either of the new layouts.

For example, set the NAME property in the Sheboygan 'Parcels' layer and zoom in.  Parcel selection is OK, but hover does not instigate the tooltip display.

**Comment by jumpinjackie** [comment]
Do you have the MapTip command in your web layout and referenced?

**Comment by jumpinjackie** [comment]
Confirming as a bug. Existing viewers still have tooltips with or without the presence of the MapTip command/widget.
