### ISSUE TITLE
Attribution Expander Has Wrong UI Element on Open

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#592]
When the [i] attribution UI button expander ">>" is pressed:

Result: the icon changes to some ?? invalid character ?? -- see screen shot below:

Expected Result: UI remains clean and aligned with other elements

![info_link_icon](https://user-images.githubusercontent.com/22054739/39927219-717e2956-5529-11e8-9ae5-6e3a7b98e708.png)

**Comment by jumpinjackie** [comment]
I'm guessing it's something with the webpack production build screwing up these characters.

**Comment by Crispin-at-Linknode** [comment]
I’m seeing it on my build – so not sure it is repeated on a production release

**Comment by jumpinjackie** [comment]
Ok I see the problem now
