### ISSUE TITLE
Buffer Task Errors

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#60]
I thought I had seen this working perviously??

When selecting a feature and navigating to the "Buffer" task, the following message is displayed in the "index.html" layout (the resource file "Resources/mapguide_en.res" does exist in \MapGuide31\Web\www\mapagent\Resources).  Config problem???

Failed to load the resource file "Resources/mapguide_en.res" for locale "en". 
Failed to load the resource file "Resources/mapguide_en.res" for locale "en". - MgInitializeWebTier line 131 file InitializeWebTier.cpp - MgInitializeWebTierInternal line 102 file InitializeWebTier.cpp - MgResources.LoadResources line 338 file c:\working\build_area\mapguide\3.1.0\x64\mgdev\common\foundation\System/Resources.cpp

**Comment by jumpinjackie** [comment]
I get a feeling it is this problem: https://trac.osgeo.org/mapguide/ticket/2224

**Comment by Crispin-at-Linknode** [comment]
Tried a lot of combinations of service / app pool and web site (IIS) restarts and recycles and still no buffer in new react layouts.
Running "classic" AJAX viewer shows buffer options, even after error is displayed in react, implying that the whole of the MG service is not compromised as ticket 2224 implies.
Are you getting replication?

**Comment by jumpinjackie** [comment]
Do you have a particular reproduction step? I'm not getting it.

**Comment by jumpinjackie** [comment]
Ok, I see it.

It happens on the "production" build. The first error is a PHP one relating to MgInitializeWebTier, and because of the referenced ticket, subsequent requests give the error message you just described.

**Comment by jumpinjackie** [comment]
And the reason this slipped under my radar is because my dev environment had webconfig.ini 4 levels down, so Common.php worked for me in dev mode

**Comment by Crispin-at-Linknode** [comment]
Still not getting it!... I tried a new checkout (I use SVN, but they come as files and build OK) AND I also tries the release ZIP file unzipping.  Both my build and release version fail on the buffer task.

Additionally, my build does not load task panels now with an invalid path being created like below (this DOES work is I deploy your prebuilt release.zip version):
http://localhost/mapguide31/viewer/localhost/mapguide31/viewer/localhost/mapguide31/phpviewersample/...

It should be regular deployment following the readme
 1) checkout source
 2) npm build  (though notes should say you need a copy of node installed of course) 
 3) setup a virtual "viewer" dir in IIS, under MG pointing to the viewer
 4) change folder permissions if required
 5) open in browser

**Comment by jumpinjackie** [comment]
Can you verify your viewer/server/common/Common.php has the changes as per de762fd ?

Also the prebuilt release ZIP is ancient now. The code is 52 commits ahead as of this post.

**Comment by Crispin-at-Linknode** [comment]
OK, my PHP was correct and I also tried to hardcode the path to webconfig.ini in the PHP.
My task panels are not loading at all with the duplicate paths:
http://localhost/mapguide31/viewer/localhost/mapguide31/viewer/localhost/mapguide31/viewer/server/Buffer/

but if I copy the frame source and edit the paths in a new tab to:
http://localhost/mapguide31/viewer/server/Buffer/

Then it's all OK... so what is building the invalid path for the task panel URLs?
