### ISSUE TITLE
Select Polygon and Radius Do Not Work if in Selection Mode

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#72]
If the "arrow" select mode is current when instigating a Select Radius or Select Polygon mode then the last point clicked invoked an XY-selection and not the expected results of the broader (radius/polygon) selection.
If another mode is current, e.g. "pan" then Radius/Polygon selection results are as expected.

Tested on IE

**Comment by jumpinjackie** [comment]
It's because of #29 

Need to find a way to unset the active tool if it's select
