### ISSUE TITLE
Potentially incorrect feature sub-selection

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#804]
I have received reports that the feature sub-selection may be highlighting the wrong feature. That is: The attributes of the current feature does not reflect what was sub-selected.

**Comment by RenoSun** [comment]
Yes, I have the same issue as well! :)

**Comment by jumpinjackie** [comment]
Are your selection problems coming from Oracle layers by any chance?

**Comment by RenoSun** [comment]
The layers coming from SQL Server 2016, and I built the Configuration Document to link to each table.

**Comment by jumpinjackie** [comment]
@RenoSun Could I trouble you with a minimal SQL Server db extract + MapGuide package that demonstrates the problem? You can just provide tables with only the id/geometry columns and only a subset of the rows.

**Comment by RenoSun** [comment]
Hi @jumpinjackie 
I hope this is what you're looking for :)
[TestParcel.zip](https://github.com/jumpinjackie/mapguide-react-layout/files/3238463/TestParcel.zip)

**Comment by RenoSun** [comment]
Hi @jumpinjackie,

I really hope this will help you to figure what's wrong. I tried to export only the data with ID and GEOM, but it seems not creating the same issue. So I decided to give you the data more than two columns including values with html (hyperlink). I found the highlight error doesn't occur occasionally when you select small amount of features on the map, but definitely found the wrong highlighting when selecting more than 10 features on the map. We're still using AIMS 2017, and I don't know if that may cause any issues with the mapguide-react-layout,
[TestParcel.zip](https://github.com/jumpinjackie/mapguide-react-layout/files/3238563/TestParcel.zip)

Please see the following GIF:
![ezgif com-optimize](https://user-images.githubusercontent.com/5566783/58661123-eac8fd00-82db-11e9-8879-3ef292b60451.gif)

**Comment by jumpinjackie** [comment]
@RenoSun I was finally able to take a look at your dataset and was able to reproduce the inconsistent sub-selection. This was the offending selection inferred from your provided gif (I'm posting this for future reference for myself).

![2019-07-31 01_16_34-TestParcel - Brave](https://user-images.githubusercontent.com/563860/62145489-e9956a00-b336-11e9-9005-92c3ff1ec07d.png)

I have a worrying suspicion that this sub-selection feature was built on a fatally-flawed assumption that the `<SelectFeatures>` content would be **rendered out in the same order** as the selection keys under `<FeatureSet>`. Further debugging will prove if this is the case.

**Comment by jumpinjackie** [comment]
Ok, here's the deal.

I have a fix, but this requires a new version of `QUERYMAPFEATURES` to support this (which I've put together in this RFC: https://trac.osgeo.org/mapguide/wiki/MapGuideRfc176).

Because the fix requires a new API, it means I have to remove support for this feature on versions older than MGOS 4.0 as I cannot rely on array index lookup to correctly find the corresponding feature selection key (which is how feature sub-selection is currently implemented).

The fix is parked on a feature branch pending approval/adoption of the above RFC.
