### ISSUE TITLE
error install mapguide-react-layout 0.6.1

### ISSUE THREAD

**Issue by estudiocad** [jumpinjackie/mapguide-react-layout#81]
hello all, after long use MapGuide again, I'm trying to install react but I have this error, Can somebody help me? 

http://localhost:8008/mapguide/viewer/

An error occurred during startup 
t is undefined 

Stack Trace 

    y@http://localhost:8008/mapguide/viewer/dist/viewer.js:81:24036
    g/<@http://localhost:8008/mapguide/viewer/dist/viewer.js:81:24119

 sorry for my english. 

oscar

**Comment by jumpinjackie** [comment]
Ok, I think I know what's happening.

You need to pass in a `resource` parameter which points to a Web Layout or Application Definition

Example: `http://localhost:8008/mapguide/viewer/?resource=Library://Samples/Sheboygan/Layouts/SheboyganPhp.WebLayout`

I'll update the viewer to make this requirement clearer

**Comment by estudiocad** [comment]
hi now this error

http://localhost:8008/mapguide/viewer/?resource=Library://Samples/Sheboygan/Layouts/SheboyganPhp.WebLayout

An error occurred during startup
Malformed input. Expected ResultColumns element

Stack Trace

    e@http://localhost:8008/mapguide/viewer/dist/viewer.js:8:13636
    k@http://localhost:8008/mapguide/viewer/dist/viewer.js:24:16101
    F@http://localhost:8008/mapguide/viewer/dist/viewer.js:24:17047
    U@http://localhost:8008/mapguide/viewer/dist/viewer.js:24:17637
    B@http://localhost:8008/mapguide/viewer/dist/viewer.js:24:18168
    Q@http://localhost:8008/mapguide/viewer/dist/viewer.js:24:21409
    MapGuide</c</e.prototype.get/</<@http://localhost:8008/mapguide/viewer/dist/viewer.js:81:25981

**Comment by jumpinjackie** [comment]
Something sounds strange with your Web Layout (it looks like it has an invalid search command)

Can you paste/attach the XML for your `Library://Samples/Sheboygan/Layouts/SheboyganPhp.WebLayout`

**Comment by estudiocad** [comment]
hello if, had a search command, delete it and it worked.
As you would have to put a command to search for items? thks a lot

**Comment by jumpinjackie** [comment]
Please note: search commands should work, but the one in your Web Layout was invalid because we were expecting some output columns defined in that search command, but the viewer didn't find any (which is what the `Expected ResultColumns element` error is)

**Comment by estudiocad** [comment]
ok thks, as it would be the url to load aqua or sidebar?

**Comment by jumpinjackie** [comment]
Only certain templates support Web Layouts and certain templates support Application Definitions

See [https://github.com/jumpinjackie/mapguide-react-layout/blob/master/TEMPLATES.md](TEMPLATES.md) for what is supported
