### ISSUE TITLE
Menu Does Not Correctly Display Base Layer Groups / Layers

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#84]
Base layer groups and menus should appear in the legend, respecting the appropriate settings in the 

Actual Behaviour:
All base layers / groups appear in the legend irrespective of 
 * appearance due to correct scale (of layer visibility range)
 * appearance due to .MapDefinition settings (e.g. show in legend) of base layers

Expected Behaviour:
Scale and UI control settings should be respected the user experience legend

**Comment by jumpinjackie** [comment]
I can see the case of DisplayInLegend not being respected, but I can't see the case of legend visibility (due to scale ranges) not being respected. Using the Sheboygan base map as an example, I see the Parcels showing up in the legend when I enter the visibility range of the Parcels layer.

**Comment by Crispin-at-Linknode** [comment]
Maybe it's a more complex example - it was a map with a couple of base layer groups, each with several layers in.  I'll see if my colleague Minh can create a simple replication case with the Sheboyban data as a string point

**Comment by minhnguyenlinknode** [comment]
Hi,

As Crispin said, I have attached here the .MapDefinition testing file of Sheboygan data.

We can quickly compare the different between Ajax Viewer and React Viewer. Basically we are unable to hide the base layer group when unchecked it from the legend in React viewer. The scale bar seems not to be working properly like in Ajax viewer.

Thanks,
[Sheboygan_Test.zip](https://github.com/jumpinjackie/mapguide-react-layout/files/575986/Sheboygan_Test.zip)

**Comment by jumpinjackie** [comment]
Ok, I see the problem.

I failed to take into consideration [my own blogged observations about how scale range visibility is calculated](http://themapguyde.blogspot.com.au/2013/03/mapguide-tidbits-scale-range-gotcha.html).

The legend needs to use `min <= scale < max` range check for testing layer item visibility.

**Comment by minhnguyenlinknode** [comment]
I think it seems not to fixed.
I have updated latest code from Github and rebuild it and still get the same error? (attached image)

![reactviewerbug](https://cloud.githubusercontent.com/assets/9201108/20122525/5b32844a-a610-11e6-9708-31eee936b3b7.png)

**Comment by jumpinjackie** [comment]
The scale bar thing is most likely #86 

I can reproduce the inability to toggle the base layer group. Working on a fix.

**Comment by Crispin-at-Linknode** [comment]
Thanks, we've got a site we can switch to react from Ajax once we get a few niggles sorted. Another great project!

Linknode
121 George Street, Glasgow G1 1RD
t: +44 141 559 6170
m: +44 7703 442 059
www.linknode.co.uk

Sent from my Windows Phone, please excuse some brief formatting.
________________________________
