### ISSUE TITLE
Wrong values "not geodesic" measurement.

### ISSUE THREAD

**Issue by loshhilov** [jumpinjackie/mapguide-react-layout#940]
Wrong values "not geodesic" measurement:
![issue](https://user-images.githubusercontent.com/25501987/62918833-87fae400-bda9-11e9-8c9f-7a04232e0852.PNG)

**Comment by jumpinjackie** [comment]
Note: The measure code is derived from the [OpenLayers measure example](https://openlayers.org/en/latest/examples/measure.html?q=measure), Do you still get these incorrect values in pure OpenLayers?

**Comment by loshhilov** [comment]
It is tested today on clean Mapguide Open Source 3.1.2 + fresh assembly of mapguide-react-layout from master branch

**Comment by loshhilov** [comment]
Measurement in OpenLayers measure example works correctly, at any latitude.
Measurement in react-viewer is correct too if the option 'Use geodesic measure' is checked.
At switched-off 'Use geodesic measure', it seems, that the amendment on width is not considered.

**Comment by jumpinjackie** [comment]
When I derived this from the OpenLayers measure example, it had the geodesic measure toggle.

When I look at that example now, that toggle no longer exists. So I'm inclined to just remove the non-geodesic measure option. Do you need non-geodesic measurement?

**Comment by loshhilov** [comment]
No, are not necessary. Thanks!
