### ISSUE TITLE
TODO: Coordinate Tracker widget

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#97]
This is another missing Fusion widget

**Comment by esnauffer** [comment]
Hi jumpinjackie, 

Thank you so much for your work! 

We are using your mapguide-react-layout and we need the coordinate tracker widget working as in the Fusion version. Do you have any idea when this widget will be implemented in mapguide-react-layout? Can we help?

Thank you!
Jenny

**Comment by jumpinjackie** [comment]
This is currently penciled in for the next milestone, and judging by the frequency of previous releases I'm looking at a new release early/mid September.

**Comment by jumpinjackie** [comment]
Aaaaaaaaand it's back (in the next release)

![coord-tracker](https://user-images.githubusercontent.com/563860/29469129-5069125a-848a-11e7-81d0-9d0fe01b1b9d.gif)
