### ISSUE TITLE
Optimization of a legend-tree

### ISSUE THREAD

**Issue by loshhilov** [jumpinjackie/mapguide-react-layout#997]
Current "folder-horizontal" icon has no functionality.
I suggest you simplify a little the tree.

My quick-drawn example (flat, one color):

![example](https://user-images.githubusercontent.com/25501987/67664303-74a6f000-f978-11e9-814f-c93c8d4cdfa7.PNG)

**Comment by loshhilov** [comment]
Thank you, I 'm closing this issue.
I just wanted to see an appropriate interface in the modern viewer.
I look forward to developing mapguide-react-layout as a basic viewer.
If you don 't mind, sometimes I 'll post my comments.

**Comment by jumpinjackie** [comment]
As this is slightly related to your original request, the work in #1041 replaces all the non-theme-rule icons with SVG equivalents like so:

![2019-12-11 01_39_03-Slate - Brave](https://user-images.githubusercontent.com/563860/70539012-2449c180-1bb7-11ea-9a29-a1c3fe97b256.png)

The motivation for this change is to allow a base icon size to be specified in the Legend, and have all the (now vector) icons scale accordingly (with the theme rule icons size being specified as part of the `CREATERUNTIMEMAP` request the viewer does on init), allowing to have all legend icons bigger than `16x16` if your application requires it.
