### ISSUE TITLE
Scale Divider value (scale-display)

### ISSUE THREAD

**Issue by loshhilov** [jumpinjackie/mapguide-react-layout#998]
The divider numbers currently display fixed Scale List values defined in Map Definition.
This is only true for the latitude of the equator.

I think this will be difficult to do, given all the unit conversions, but the ideal scale value should change dynamically for arbitrary latitude:
ScaleDividerValue = FiniteScaleValue * cos(AverageCurrentExtendLongtitudeInDegrees)

**Comment by jumpinjackie** [comment]
This doesn't sound like a viewer problem, more a problem that when [MapGuide Maestro](https://github.com/jumpinjackie/mapguide-maestro) generates a scale list for a Map Definition that it be smarter about how that list is generated and consider the geographical bounds of the map when doing it.

**Comment by loshhilov** [comment]
Ok, i close this issue
